### ISSUE TITLE
beanstalkd

### ISSUE THREAD

**Issue by dmolina-ot** [NREL/api-umbrella#113]
Why would we use beanstalkd?

**Comment by GUI** [comment]
[beanstalkd](http://kr.github.io/beanstalkd/) is a lightweight job queue. It is used to process the logs for analytics purposes. On every API hit, we add an item to the beanstalkd queue to process that request's log data. This primary purpose of this job is to coordinate logging among various pieces of the stack. This allows us to coalesce log information from these different pieces, and then perform various bits of post-processing on that log data (for example, geocoding the IP and performing further parsing/analyzing of the user agent information). After this processing finishes, the log data is inserted into our analytics database (elasticsearch), and then the job is removed from the beanstalk queue. This job queue allows us to reliably process the log data asynchronously from the request happening (so we don't hold up the request or response while trying to log all this data on the fly). This is why there's usually a few seconds delay between when a request happens and when the request shows up in the analytics screens.

Our use of Beanstalk is actually a recent change, though. Previously, we were processing logs in a very similar fashion, but we were using Redis for the job queue. While you can do job queuing in Redis, Redis is a much more generic data store, so job-queue specific functionality can be a little cumbersome to implement and filled with edge-case issue (job locking, handling failures, delaying jobs, etc). Beanstalk is purpose-built to be a job queue, so it handles a lot of these things in a much more straightforward, reliable way (in my opinion). While I was definitely hesitant to add another component to the mix, beanstalk is very light weight, and it also solved a number of corner-case issues we had run into with our previous Redis-based job queue implementation.

I hope that helps explain things, but let me know if you have any other questions.

**Comment by imi-apimanager-test** [comment]
Then, why would we use Redis?

**Comment by GUI** [comment]
beanstalkd and redis are no longer being used in the v0.9 release. We're using heka for queuing analytics logs now, which greatly simplifies this: https://github.com/NREL/api-umbrella/pull/183
