### ISSUE TITLE
Balancing API Backends

### ISSUE THREAD

**Issue by imi-apimanager-test** [NREL/api-umbrella#117]
I don't undestand how I must configure two balanced Backends with the admin console. I can add multiple servers in Backend section, but in the next section, Host, I only can define one Backend Host, then all the request are consumed by this backed and the load balancing doesn't work.

**Comment by imi-apimanager-test** [comment]
For example:
I have two backend servers with the same API:
http://www.myapiserver1.com
http://www.myapiserver2.com

And I have de API-Umbrella in a server: www.myapimanager.com

In the API Backend configuration:
Servers:
http://www.myapiserver1.com
http://www.myapiserver2.com

Host:
Frontend Host: www.myapimanager.com

But, which is the Backend Host?

**Comment by GUI** [comment]
Very sorry for the delay in responding!

So the "Backend Host" field only dictates how the `Host` HTTP header is rewritten on the requests that your backend servers receive. It's a single value to standardize the requests and which Host the different backend servers must be listening to. If your backend servers are listening to all hosts, then the backend host field doesn't actually matter. However, if your backend servers are using name-based virtual hosts to respond differently to different domain names, then this "Backend Host" field must match whatever your backend servers are listening to.

For example, in this example case, you could also define the "Backend Host" to be "www.myapimanager.com", but then both your myapiserver1.com and myapiserver2.com servers must be setup to listen to for either all virtual host names, or "www.myapimanager.com" explicitly.

Does that make sense?

**Comment by dmolina-ot** [comment]
This is rare!
Then how is teh natural way to define API balanced?

**Comment by GUI** [comment]
In a typical setup, if your frontend host is www.myapimanager.com and the backend servers are http://www.myapiserver1.com and http://www.myapiserver2.com, then you'd typically also define your backend host to also be www.myapimanager.com. Then you'd just need to make sure that your actual backend servers are listening for that domain name. If they're listening to all hostnames, then you may not need to do anything else, but if they're using name-based virtual hosting at the Apache or nginx level, then you'd have to configure that there. Let me know if you still have any other questions or issues with this.

**Comment by dmolina-ot** [comment]
Thank you!
It's fine.
