### ISSUE TITLE
Multi-Node Deployment Documentation

### ISSUE THREAD

**Issue by rholloway** [NREL/api-umbrella#125]
I was wondering if there is any documentation anywhere on setting up a multi node cluster for api-umbrella. I just discovered API Umbrella and it seems to offer what we are looking for but some documentation I have seen is pretty limited to a basic install (one node running all services).

What we are looking at doing is running the routing / web services behind an ELB in AWS, and then spin up a small cluster for db related checks /activity (mongo/es/redis). Our primary goal for scaling horizontally is stability and availability. I'm also not sure to what extent redis is configured. I don't see it referenced under api-umbrella.yml but know it's running. Putting api-umbrella instances behind an ELB is easy but just need to make sure data stored is all in sync such as key usage and logs, hence breaking off mongo/es/redis? to a single multi node cluster.

I'm guessing I can just modify the api-umbrella.yml file and enable services router/web for one, and *_db for the other. It then looks like I may need to make some custom adjustments to /opt/api-umbrella/etc/*.conf files for the db related files in order to get those multi-node and communicating with each other. I have experience with elasticsearch clusters and can probably figure out how to make mongodb and redis work on multiple nodes, but just want to make sure I have my bases covered.

Am I missing anything? Or, if there is some documentation or example available, I can just refer to that.

**Comment by dmolina-ot** [comment]
You can see https://github.com/NREL/api-umbrella/wiki/Deployment

**Comment by rholloway** [comment]
Thanks! That helps quite a bit. The only thing I'm still confused on is the redis portion. From looking at http://nrel.github.io/api-umbrella/docs/architecture/ it made it sound like redis played a role in terms of rate limiting and/or api checks. Based on the wiki entry, it sounds like redis runs on the umbrella router behind an load balancer, but it's not distributed. 

If redis plays a role in rate limiting and/or api key usage (for quotas), I would think it would also need to be distributed in such a way that each umbrella router is essentially aware of the others and maintaining that state. If redis is just used for other caching but not so important in terms of limits and quotas (assuming those are purely dictated by mongodb), then the wiki above makes sense and production install seems a bit easier.

**Comment by dmolina-ot** [comment]
Redis works as a cach, so it musn't be distributed. You can read interesting link https://github.com/NREL/api-umbrella/issues/104

**Comment by GUI** [comment]
Very belatedly, there's a documentation page now outlining a multi-server setup: https://api-umbrella.readthedocs.org/en/latest/server/multi-server.html Let us know if there's still any questions.
