### ISSUE TITLE
API Umbrella Web and CAS (Login)

### ISSUE THREAD

**Issue by mafiu** [NREL/api-umbrella#132]
Hi,

I'm trying to configure omniauth-cas in API Umbrella Web.
I'm using API Umbrela 0.8 and omniauth-cas 1.1 (It's bundled in API Umbrella package)

I've enabled it on config/initializers/devise.rb in this part:
    when "CAS"
      config.omniauth :cas,
        :host => "sso.example.com",
        :login_url => "/cas/login",
        :service_validate_url => "/cas/serviceValidate",
        :logout_url => "/cas/logout",
        :ssl => true

The problem is that when I try to login trhounght CAS the service URL provided by API Umbrella is doubled encoded

To reproduce:

1) Go to admin login page.
2) Click on login with CAS --> https://api.example.com/admins/auth/cas
3) It's redirected to: https://sso.example.com/cas/login?service=https%253A%252F%252Fapi.example.com%252Fadmins%252Fauth%252Fcas%252Fcallback%253Furl%253Dhttps%25253A%25252F%25252Fapi.example.com%25252Fadmin%25252Flogin
4) The CAS service doesn't understand doubled encoded URL.

Do you know where I can fix it?

Thanks

**Comment by GUI** [comment]
@mafiu My apologies for the delay in response. I haven't personally experienced this when using CAS, but I found a couple of references to people encountering this with omniauth-cas when Apache was performing redirects in front of the CAS server. See: https://github.com/dlindahl/omniauth-cas/issues/7#issuecomment-27596350 and https://github.com/gitlabhq/gitlabhq/issues/4997#issuecomment-25733038 Are there perhaps any redirects happening on the CAS server side of things that might be leading to this double encoding?

If redirects don't seem to be the issue, can you share what CAS server implementation you're trying to use this against? I've only had experience setting API Umbrella against the Jasig CAS Server, so I wonder if the server implementation might play a role.

But I should note that the API Umbrella installation where I've used CAS is a bit out of date, so if it's not something simple like the redirects issue, I could also try getting a fresh API Umbrella v0.8 installation with omniauth-cas 1.1 working against our CAS server to verify things.

**Comment by mafiu** [comment]
@GUI Thanks,

I was searching in the wrong place, it's working with JASIG CAS, it was a problem with http to https redirect on the CAS Server.

Thanks!
