### ISSUE TITLE
Router Does Not Seed Initial Superusers After Dropping MongoDB

### ISSUE THREAD

**Issue by darylrobbins** [NREL/api-umbrella#137]
I shutdown API Umbrella and dropped its database using the Mongo shell. Upon restarting, the router automatically recreated the schema and seeded the default API users; but it did not reseed my initial superusers.

No errors in the log. Multiple restarts and repeating these steps with slight variations, various times did not rectify the issue.

I was able to workaround the problem by recreate my initial superusers through the Mongo shell.

**Comment by GUI** [comment]
Odd, in very briefly looking through the code, I thought the initial superusers should be seeded again if you perform a full API Umbrella restart (or at least that was the intention). I'll try to look into that this week.

**Comment by darylrobbins** [comment]
Agreed. It definitely looks like that's what the code should be doing, especially when it is seeding other data. Unfortunately, those aren't the results I have been observing.

**Comment by GUI** [comment]
I believe this should be fixed in the v0.9 release.
