### ISSUE TITLE
Cannot Disable Admin Users

### ISSUE THREAD

**Issue by darylrobbins** [NREL/api-umbrella#139]
At present, there is no way to disable an Admin User. I cannot delete them or disable them, like I can do for an API User. I can only remove their Superuser flag if I assign them to a group. However, that still gives the user some access (you can't create a group with no privileges), albeit less than they would get as a superuser.

**Comment by GUI** [comment]
Oops, this got tackled last month in #152, but I forgot to mention it here. This should be taken care of in master now.
