### ISSUE TITLE
Get user API Keys via Admin API REST interface.

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#141]
We would like to allow users to recover their API key, view it on a profile page, etc. We have tried the Admin API, but it only returns an `api_key_preview`. How can we access user API keys from the database?

**Comment by GUI** [comment]
Apologies for the delay in responding. This is a good point. Right now our API for users is geared towards the admin use-case, where we are purposefully hiding the full API key (the thought is that we're treating admins as less trusted, so not even admins can get a user's key and impersonate them). But I can definitely see how it would be useful to be able to show the owner of the API key the full key again. Ideally we'd have the user API return the full API key if the owner is hitting that API endpoint. Have you implemented user login yet? I'm just wondering how that might work in your system and how we could tie that to our API.

**Comment by brylie** [comment]
It seems like there should be at least some level of trusted user, such as super admin -- for data-sync, etc.

We have implemented sign-in with Github, via the [meteor OAuth](http://docs.meteor.com/#/full/meteor_loginwithexternalservice) package.

For integration, I am writing [Meteor.js wrappers](https://github.com/brylie/meteor-api-umbrella) around all Admin API endpoints, and can use the methods to store information in our database, create [reactive data sources](http://docs.meteor.com/#/full/reactivity), etc.

**Comment by brylie** [comment]
This issue might simply be resolved by making API Keys available to superusers via the Admin API REST interface.

**Comment by GUI** [comment]
Super user admins can now view the full API keys in v0.9 (see https://github.com/18F/api.data.gov/issues/276), so it think this should solve this use-case, but let us know if not.
