### ISSUE TITLE
Working with the rate limiter

### ISSUE THREAD

**Issue by JuusoV** [NREL/api-umbrella#147]
Im currently trying to determine how  API Umbrella collects rate limiting data. 

I found the file /app/models/api/rate_limit.rb
Unfortunately my knowledge of Ruby is not sufficient to get forward with this alone.
Could you give me help to describe how the rate limiter works? How does it store the information to the Mongodb? This is very crucial for us, as we are recreating the configuration form.

**Comment by JuusoV** [comment]
@GUI Could you give me a hand on this?

**Comment by GUI** [comment]
Apologies for the delay! So just to clarify, are you referring to just the rate limit configuration data (for example, the default rate limit applied to a specific API)? Or are you also referring to the live rate limit data for api keys or IP addresses being kept track of in the proxy (for example, that a specific api key has made 150 requests in the past hour)?

I'm assuming you're referring to just the configuration data in which case, here's a few notes:

- The basic model structure is that an API Backend contains a `settings` object, which can contain some high-level rate limit settings like [`rate_limit_mode`](https://github.com/NREL/api-umbrella-web/blob/1f43fe1cc7f3ece819a028a64677e4dfd795a035/app/models/api/settings.rb#L16) (default, unlimited, or custom). In the event of a "custom" mode, then the `settings` object can contain an array of [`rate_limits`](https://github.com/NREL/api-umbrella-web/blob/1f43fe1cc7f3ece819a028a64677e4dfd795a035/app/models/api/settings.rb#L26) that reference that RateLimit model you spotted.
- Each rate limit instance defines the limit on a specific time duration (for example, allow 500 requests per hour). There's some more options on each limit, which we recently tried to document here: https://github.com/NREL/api-umbrella-gatekeeper/tree/master/config#apisettingsrate_limits
- Here's an example of how the api record with a custom rate limit would actually look as a nested object in the Mongo database: https://github.com/NREL/api-umbrella-gatekeeper/blob/f6ef66fd8d0d2a001a305fe8385410d077bfdf29/test/server/rate_limiting.js#L775-L824

I hope that helps, but let me know if you have any other questions or this isn't quite what you were looking for.
