### ISSUE TITLE
Start api-umbrella on a different port

### ISSUE THREAD

**Issue by kgrbh** [NREL/api-umbrella#155]
HI, I apologize if this is not the right place to post this. However i went through the docs and could not find this information. I want to start api-umbrella at some another port. Maybe do something like:
sudo /etc/init.d/api-umbrella start -9222
where 9222 can be the custom port. Is this available? How can i do this?
Thanks

**Comment by mafiu** [comment]
Hi @kgrbh, you can see all the values which you can define in api-umbrella.yml in https://github.com/NREL/api-umbrella-router/blob/master/config/default.yml

You can add your custom port as:
http_port: 80
https_port: 9222

**Comment by GUI** [comment]
Belatedly adding a documentation page on this: https://api-umbrella.readthedocs.org/en/latest/server/listen-ports.html
