### ISSUE TITLE
Error When Starting It On Centos 6

### ISSUE THREAD

**Issue by Hojalab** [NREL/api-umbrella#156]
`i get this error when it try to run 
on production
GLIBC_2.14' not found (required by /opt/api-umbrella/embedded/bin/node)

**Comment by GUI** [comment]
Sorry for the delay and troubles! We do most of our testing against CentOS 6, but I'm not entirely sure what's going on here. Do you think you maybe accidentally downloaded and installed the version of API Umbrella for CentOS 7 on CentOS 6? We can verify that, as well as look at your glibc version, if you run this command: `yum list api-umbrella glibc`. If the api-umbrella version listed ends with `.el7`, then I think you may just need to uninstall and then [redownload](http://apiumbrella.io/download/) and install the CentOS 6 version (make sure the file downloaded ends in `.el6`). If the version installed does already list `el6`, then would you mind sharing the rest of that command's output so we can see what version of glibc you have installed?

**Comment by GUI** [comment]
We've released new v0.9 packages (https://apiumbrella.io/install/), so I'm going to go ahead and close this, but let us know if you're still having any installation troubles.
