### ISSUE TITLE
What are required parameters for creating API Backend from Admin API?

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#164]
When creating an API Backend via the [Admin API](http://nrel.github.io/api-umbrella/docs/admin-api/), what are required parameters? This is [not currently documented](http://nrel.github.io/api-umbrella/docs/admin-api/#api-backends-api-backend-collection-post).

**Comment by GUI** [comment]
Okay, I've finally taken a stab at fully documenting the complete set of admin API endpoints in new Swagger docs. Here's the one for creating API backends: http://apiumbrella.io/docs/admin-api/#!/api/post_api_umbrella_v1_apis. For the API backends, it should boil down to the following required fields:

```
api.name
api.backend_protocol
api.frontend_host
api.backend_host
api.servers.host
api.servers.port
api.url_matches.frontend_prefix
api.url_matches.backend_prefix
```

I'd like to do more verification against this swagger spec to make sure everything is actually correct in it, but in the meantime, let me know if you're seeing any of the APIs behave not as documented.
