### ISSUE TITLE
Document required fields for AdminAPI POST requests

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#165]
While trying to [POST a new API via the Admin API](http://apiumbrella.io/docs/admin-api/#!/api/post_api_umbrella_v1_apis), we are encountering some errors:

```javascript
{
  "errors": {
    "name": [
      "can't be blank"
    ],
    "backend_protocol": [
      "is not included in the list"
    ],
    "frontend_host": [
      "can't be blank",
      "must be in the format of \"example.com\""
    ],
    "backend_host": [
      "can't be blank",
      "must be in the format of \"example.com\""
    ],
    "balance_algorithm": [
      "is not included in the list"
    ],
    "base": [
      "must have at least one servers",
      "must have at least one url_matches"
    ]
  }
}
```

Based on the above message, I have refined our request body to the following JSON:

```javascript
{
  "api": {
    "name": "Example API",
    "backend_protocol": "http",
    "frontend_host": "frontend.host",
    "backend_host": "backend.host"
}
```

Please provide us with a working example of a POST body to create an API Backend via the Admin API.

**Comment by bajiat** [comment]
Help with the issue on not being able to post an API would be much appreciated, since this is becoming a showstopper for our dashboard implementation and our public beta.

**Comment by ashakunt** [comment]
@brylie I guess, you need some more information in the POST request that you are making: I just now made a port request with the following JSON:

```
{
  "api": {
    "name": "Example ",
    "backend_protocol": "https",
    "frontend_host": "<umbrella-url>",
    "backend_host": "<backend-host-url>",
    "balance_algorithm": "least_conn",
    "url_matches": [
        {
        "frontend_prefix": "/<some-prefix1>/",
        "backend_prefix": "/<some-prefix2/"
        }
    ],
    
    "servers": [
        {
            "host": "<i-used-same-as-backend-host-url>",
            "port": 443
        }
        ]
    }
}
```

And this worked just fine. I can also see the backend API added to umbrella.

**Comment by ashakunt** [comment]
I would say that this is a false issue hence, it must be closed.

@bajiat @brylie @GUI

**Comment by elnzv** [comment]
@ashakunt doesn't work for me.
What are you using to send this requests?

**Comment by ashakunt** [comment]
@elnzv I used postman for this purpose.

**Comment by GUI** [comment]
Here's a curl example that works for me:

```
curl -v -H "X-Api-Key: YOUR_API_KEY" -H "X-Admin-Auth-Token: YOUR_ADMIN_AUTH_TOKEN" -H "Content-Type: application/json" -d '{"api":{"name":"Example","backend_protocol":"https","frontend_host":"*","backend_host":"maps.googleapis.com","balance_algorithm":"least_conn","url_matches":[{"frontend_prefix":"/example/","backend_prefix":"/"}],"servers":[{"host":"maps.googleapis.com","port":443}]}}' "https://YOUR_API_UMBRELLA_DOMAIN/api-umbrella/v1/apis"
```

Note that you'll need to use send at `Content-Type: application/json` header when POSTing the JSON body. Let me know if you're still running into any issues.

**Comment by ashakunt** [comment]
@elnzv, as @GUI mentioned, you should have the content type set to JSON and then it will work.

**Comment by elnzv** [comment]
Okay, now I works.
In postman body you need choose JSON(application/json)  (by default it is text)

**Comment by elnzv** [comment]
thanks @ashakunt @GUI !

**Comment by brylie** [comment]
@ashakunt thanks for the working example. This seems like a documentation issue now.

**Comment by brylie** [comment]
@GUI, please verify that the Admin API field requirements are different from the API Umbrella Add API form. This inconsistency is [causing some difficulty](https://github.com/apinf/api-umbrella-dashboard/issues/346) in our dashboard project.

**Comment by brylie** [comment]
Sorry for the confusion, we realize now that our schema does not match the API Umbrella model.
