### ISSUE TITLE
Offer containerized installation package option

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#167]
# Feature request
Create a containerized installer for API Umbrella, including possibly separate containers for dependencies. E.g. offer a Docker container/installer.

# User story
As a system admin
I would like to install API Umbrella and its dependencies via some container format
so that I can effectively manage my companies server resources

# Related issue(s)
This feature has been briefly mentioned in issue #26, but was not given full fledged feature request status.

**Comment by brylie** [comment]
It might prove useful to create a [Panamax](http://panamax.io) server template for the API Umbrella system. Here is a brief demonstration video:

![http://img.youtube.com/vi/koAwYsyP5-w/maxresdefault.jpg]()

**Comment by brylie** [comment]
There is a [pull request open with a Dockerfile](https://github.com/NREL/api-umbrella/pull/178).

**Comment by GUI** [comment]
A docker container for v0.9 is now published and I've added instructions here: https://api-umbrella.readthedocs.org/en/latest/getting-started.html#running-with-docker I'm not a docker expert, though, so let me know if you have any feedback or suggestions for any of this.
