### ISSUE TITLE
Show API Umbrella version on admin site

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#169]
# User story
```
As an administrator
I want to check the version(s) of API Umbrella and other related platform technologies
so that I can make sure our platform is up-to-date
```

# Feature
Create a page, or page element, to show the version number(s) of API Umbrella and other stack technologies.

**Comment by cmc333333** [comment]
Excellent idea

**Comment by GUI** [comment]
Whoops, I forgot to add this to the milestone, but a footer in the admin has been [added](https://github.com/NREL/api-umbrella/commit/cecc44ef201c082991ec9c8988ad5c8fe6b5242c) which notes the current version, and this is part of the v0.10 packages that came out today.
