### ISSUE TITLE
VM: Git Version outdated

### ISSUE THREAD

**Issue by cmc333333** [NREL/api-umbrella#181]
To `make` the lua branch, I needed an update git. The version within the umbrella VM is 1.7.1.

Unfortunately this version of CentOS doesn't have updated libs, so @GUI had me put

```
[WANdisco-git]
name=WANdisco Distribution of git
baseurl=http://opensource.wandisco.com/centos/6/git/$basearch
enabled=1
gpgcheck=1
gpgkey=http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco
```

in `/etc/yum.repos.d/WANdisco-git.repo` to get the latest.

Otherwise, the build process hangs on:
```
cp build/mora_glide.yaml deps/gocode/src/github.com/emicklei/mora/glide.yaml
cd deps/gocode/src/github.com/emicklei/mora && PATH=/home/vagrant/api-umbrella/deps/golang-1.5.1/bin:/home/vagrant/api-umbrella/deps/gocode/bin:/vagrant/workspace/router/bin:/opt/api-umbrella/sbin:/opt/api-umbrella/bin:/opt/api-umbrella/embedded/sbin:/opt/api-umbrella/embedded/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:./node_modules/.bin/:/home/vagrant/bin GOPATH=/home/vagrant/api-umbrella/deps/gocode GOROOT=/home/vagrant/api-umbrella/deps/golang-1.5.1 GO15VENDOREXPERIMENT=1 glide update
[INFO] Fetching updates for github.com/compose/mejson.
[INFO] Fetching updates for github.com/emicklei/go-restful.
[INFO] Fetching updates for github.com/magiconair/properties.
[INFO] Fetching updates for gopkg.in/mgo.v2.
```

**Comment by GUI** [comment]
Yup, just for reference, it looks like git 1.7.3+ is required (and CentOS 6 only packages 1.7.1). This is needed for the fetching from gokg.in since it performs a redirect which older versions of git don't support. Reference: https://groups.google.com/d/msg/golang-nuts/RKz9ASmJm3o/o7NcNY6x8U0J

**Comment by GUI** [comment]
This is part of the current vagrant setup now: https://api-umbrella.readthedocs.org/en/latest/developer/dev-setup.html
