### ISSUE TITLE
Admin API: "override_response_headers_string" field

### ISSUE THREAD

**Issue by jykae** [NREL/api-umbrella#186]
Just a Question: Will this reset whatever there is in Response Headers?

**Comment by GUI** [comment]
Sorry for the delay in following up. Yes, the override headers option will replace any existing values for that header in the response. Here's the descriptions we provide in the [tooltip help](https://github.com/NREL/api-umbrella/blob/9bc593600fb06e1699ed6af4dbebbc3a460f1481/src/api-umbrella/web-app/config/locales/en.yml#L150-L167) for the two response header fields:

**Default Response Headers**
> Define header values that will be set in the response regardless of whether the header is already set in the response.
> 
> For example, to set default CORS headers on all responses that don't explicitly set their own CORS headers:
> 
> ```
> Access-Control-Allow-Origin: *
> ```

**Override Response Headers**
> Define header values that will be set in the response regardless of whether the header is already set in the response.
> 
> For example, to force CORS headers on all responses:
> 
> ```
> Access-Control-Allow-Origin: *
> ```

Let us know if anything still isn't clear with this.
