### ISSUE TITLE
Adding an API with the host name of the API Umbrella Server renders 404 for Admin and Portal pages

### ISSUE THREAD

**Issue by DonMartin76** [NREL/api-umbrella#193]
These couple of steps quite effectively kill an API Umbrella instance (at least the one I am using on Azure):

* Create a new API Backend
* Use the host name of the API Umbrella server as frontend ("listen to") IP, e.g. api-umbrella.myhoster.com
* Add a pattern for the API
* Publish the API

This immediately kills the Admin and Portal pages; all pages are rendered as generic 404 not found pages. The actual API will work though (I checked that using a REST client).

**Comment by GUI** [comment]
Sorry about that! This should be fixed in the next release. In the meantime, see here for a workaround you can implement in your config file: https://github.com/NREL/api-umbrella/issues/192#issuecomment-155685542

**Comment by DonMartin76** [comment]
Thanks for the workaround; will try that tomorrow.

**Comment by DonMartin76** [comment]
Works with the workaround. Thanks.
