### ISSUE TITLE
Upgrade path from 0.8?

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#200]
After we upgraded to 0.9 and rebooted the system, we get the following error:

```
/etc/init.d/api-umbrella: line 41: api-umbrella: command not found
```

As a result, the API Umbrella service will not load.

**Comment by GUI** [comment]
Can you try runninng the following commands and posting the output?

```
ls -l /usr/bin/api-umbrella*
ls -l /opt/api-umbrella/bin
```

**Comment by brylie** [comment]
Sorry for the delay in response, we got the 'broken' upgrade VM back online today. Here are the results of the commands you posted:

```bash
# ls -l /usr/bin/api-umbrella*
ls: cannot access /usr/bin/api-umbrella*: No such file or directory
```

```bash
$ ls -l /opt/api-umbrella/bin
total 0
lrwxrwxrwx 1 root root 46 marra 28 03:10 api-umbrella -> ../embedded/apps/core/current/bin/api-umbrella
```

**Comment by brylie** [comment]
Additionally, the following commands return nothing:

```
$ sudo ls -l /usr/bin | grep api
$ sudo ls -l /usr/bin | grep umbrella
```

**Comment by brylie** [comment]
If I understand where you are going with this, I ran the following commands:

```sh
$ sudo ln -s /opt/api-umbrella/bin/api-umbrella /usr/bin/api-umbrella
$ sudo service api-umbrella start
  * Starting API Umbrella api-umbrella 
```

Still, the API Umbrella application does not load when requesting the server through a web browser.

**Comment by brylie** [comment]
We are trying the upgrade again with the following steps:

```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

$ sudo apt-get update && sudo apt-get upgrade -y
```

**Comment by brylie** [comment]
Warnings during this process:

```
Unpacking api-umbrella (0.9.0-1~trusty) over (0.8.0-1) ...
dpkg: warning: unable to delete old directory '/opt/api-umbrella/embedded/apps/web/shared/log': Directory not empty
dpkg: warning: unable to delete old directory '/opt/api-umbrella/embedded/apps/web/shared': Directory not empty
dpkg: warning: unable to delete old directory '/opt/api-umbrella/embedded/apps/web': Directory not empty
```

**Comment by brylie** [comment]
Then, some configuration overwrite messages:

```
Configuration file '/etc/init.d/api-umbrella'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** api-umbrella (Y/I/N/O/D/Z) [default=N] ?
```

```
Configuration file '/etc/logrotate.d/api-umbrella'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer
...
```

I answered **Y** to both.

**Comment by GUI** [comment]
Thanks for reporting this. I've identified a couple issues with the upgrade process and some extra files being marked as config files in the `.deb` packages. I think we should have new packages released Monday or Tuesday to resolve these issues.

**Comment by GUI** [comment]
This has been fixed in https://github.com/NREL/api-umbrella/commit/629dc347f930b65fb963d7d372dae9368783a64b New v0.10 packages will be released tomorrow, which should make upgrading as easy as `apt-get install api-umbrella`.

**Comment by GUI** [comment]
v0.10 packages are now [published](http://apiumbrella.io/install/). Give a shout if you're still having any trouble upgrading.

**Comment by brylie** [comment]
@GUI, I ran the install process using 0.10 packages on an 0.8 instance. The install seems to have succeeded, but the ApiUmbrellaWeb service does not respond to requests to `/` or `/admin`. 

Additionally, I got an error when I tried to upgrade instead of install:

```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  api-umbrella
```

**Comment by GUI** [comment]
@brylie: After upgrading, can you try running `sudo /etc/init.d/api-umbrella start`? Sorry I forgot to mention that, but if you're upgrading from v0.8 on Ubuntu or Debian, you have to explicitly start API Umbrella again after upgrading. This shouldn't be an issue moving forward, since we're now explicitly testing the various upgrade paths for packages, but due to the post-removal package scripts in v0.8 and the ordering of callbacks for `.deb`s, you'll need this manual start after upgrading this time (and we can't do much to solve it, since it's an issue with the v0.8 package).

Let me know if that doesn't do the trick, though.

Regarding `apt-get upgrade` not working, based on http://askubuntu.com/a/602, I think that's maybe expected since we had to [add a dependency](https://github.com/NREL/api-umbrella/commit/3cdbe1f5bf19874d367577206878409aebda724c) to the packages. It sounds like any dependency changes might trigger this, so `apt-get install api-umbrella` should probably be the preferred way to update the package (`api-get upgrade` also tries to update the whole system, so that may update more packages than you want).

**Comment by brylie** [comment]
@elnzv [reported that he was able to successfully upgrade from 0.8 to 0.10](https://github.com/apinf/api-umbrella-dashboard/issues/669#issuecomment-165096673), and will test on a clone of our main VM.

**Comment by jykae** [comment]
tailf /var/log/api-umbrella/nginx/current is looping error:

[emerg] 17617#0: could not build the server_names_hash, you should increase server_names_hash_bucket_size: 32

@GUI any idea how I could fix this ? where I can find "server_names_hash_bucket_size" ?

**Comment by brylie** [comment]
@gui, may we please re-open this issue until we have a successful upgrade path?

**Comment by brylie** [comment]
@jykae the hash_bucket_size issue was [discussed and marked as resolved here](https://github.com/NREL/api-umbrella/issues/168).
