### ISSUE TITLE
0.9 install: fatal: unable to acquire lock on/opt/api-umbrella/var/run/perpboot.pid: temporary i/o failure (EAGAIN)

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#203]
After installing 0.9 and editing the api-umbrella.yml file, we get the following error when starting the service:

```
$ sudo service api-umbrella start
 * Starting API Umbrella api-umbrella
 runtool: fatal: unable to acquire lock on/opt/api-umbrella/var/run/perpboot.pid: temporary i/o failure (EAGAIN)
```

**Comment by brylie** [comment]
This may be resolved by using `restart` instead of `start`, but I have not tested this difference.

**Comment by GUI** [comment]
This message would show up if the service was already started and you ran the `start` command again. This is improved in https://github.com/NREL/api-umbrella/commit/629dc347f930b65fb963d7d372dae9368783a64b. Now if you run the start command when api umbrella is already started or the stop command when api umbrella is already stopped, you'll get a more instructive message. This will be part of v0.10 which will be released tomorrow.
