### ISSUE TITLE
Where are the new repositories based on the new architecture?

### ISSUE THREAD

**Issue by rezadehganpour** [NREL/api-umbrella#205]
I want to install new API umbrella(The new architecture with the two repositories) from source the source code. can you please point me to the right repositories, branches or tags that I can need to use?

**Comment by cmc333333** [comment]
Hi @rezadehganpour , you're in the right repo now, and the `master` branch contains the new architecture.

The vagrant file is probably the easiest to get started with -- more thorough instructions here: https://api-umbrella.readthedocs.org/en/latest/getting-started.html

**Comment by rezadehganpour** [comment]
Thanks @cmc333333
However I want to install umbrella from the source code. I tried this url from your website http://api-umbrella.readthedocs.org/en/latest/compiling-from-source.html but it was no good! can you please point me to the correct two repos.
I installed the old architecture umbrella from the source code as well, now I want to upgrade it with the new one.

**Comment by cmc333333** [comment]
@rezadehganpour Sorry, we need to fix that link. Try https://api-umbrella.readthedocs.org/en/latest/developer/compiling-from-source.html instead

**Comment by rezadehganpour** [comment]
Thanks that worked!

**Comment by GUI** [comment]
Thanks for spotting this broken link! Sorry for the confusion, but the link should now be [fixed](https://github.com/NREL/api-umbrella/commit/06be84ba7a12dd71c549141a0efee14b12ad4943).
