### ISSUE TITLE
Unable to access the web admin account

### ISSUE THREAD

**Issue by tinu85** [NREL/api-umbrella#207]
I have followed the installation instructions for Ubuntu 14.04(Trusty),however i am unable to login to the web admin using https://10.1.114.64/admin/ where 10.1.114.64 is my API Umbrella host,i tried to login with Mozilla Persona ,i got verified in Mozilla ,but i get the following error message finally :  
The account for 'tinu.elizabeth@quest-global.com' is not authorized to access the admin. Please contact us for further assistance.

Please Note: I have added the email id in the api-umbrella.yml config file as well

**Comment by GUI** [comment]
@tinu85: Did you happen to edit the `/etc/api-umbrella/api-umbrella.yml` file to add your e-mail address *after* you had already started API Umbrella? That's one reason I could think of that your initial account might not be working. You could try running `sudo /etc/init.d/api-umbrella restart` and logging again to see if that works.

If it's not that, then I'd maybe check the formatting and indentation of your `/etc/api-umbrella/api-umbrella.yml` file. Does it look like this?

```yaml
web:
  admin:
    initial_superusers:
      - tinu.elizabeth@quest-global.com
```

**Comment by mitchellfranklin** [comment]
I am also getting this error, I have made sure the file like above (Except for the # in front of the lines) is the same

**Comment by GUI** [comment]
@mitchellfranklin: So do you mean that you do have `#` symbols in front of the lines? In other words, does your file look like?

```
# web:
#   admin:
#     initial_superusers:
#       - your-email@example.com
```

If so, those `#` symbols are comments in YAML files, so you'll actually need to remove those to uncomment the lines (so they are effective):

```
web:
  admin:
    initial_superusers:
      - your-email@example.com
```

You'll then need to restart API Umbrella after making any changes to this file (`sudo /etc/init.d/api-umbrella restart`).

But if I'm misunderstanding, or you're still running into any issues with those lines uncommented, let us know.

**Comment by mitchellfranklin** [comment]
No that is perfect - I thought it might be the case however the doco from what I can see does not state removing the # just to add in your email - thanks heaps

**Comment by tariq452** [comment]
it's give me same error API key signup unexpectedly failed

services:
   - general_db
   - log_db
   - router
   - web
 web:
   admin:
     initial_superusers:
       - tariq.a.tami@gmail.com
     auth_strategies:
       enabled:
         - github
         - google
         - persona
       github:
         client_id:
         client_secret:
       google:
         client_id:
   client_secret:
 elasticsearch:
   hosts:
     - http://127.0.0.1:14002
 mongodb:
   url: mongodb://127.0.0.1:14001/api_umbrella
 nginx:
   workers: 4
 gatekeeper:
   workers: 4

**Comment by coobr01** [comment]
I'm having the same issue. I'm using Docker on Windows but I do have the correct entry in /etc/api-umbrella/api-umbrella.yml

```
web:
  admin:
    initial_superusers:
      - test.test@test.com
```

when I access https://127.0.0.1/admin

I don't get an option to login. 

![image](https://cloud.githubusercontent.com/assets/1842830/21531132/b513d62e-cd13-11e6-98e9-c493deac6a9a.png)

**Comment by GUI** [comment]
@coobr01: Since Persona recently shut down, you'd need to setup one of the other login options. However, if you're just interested in testing, see https://github.com/NREL/api-umbrella/issues/323 for a potential workaround. (However, we're also working on a local login option to make this easier in the next release.)

**Comment by coobr01** [comment]
Thanks, that worked. The app_env: development parameter should probably be added to the setup section at [https://api-umbrella.readthedocs.io/en/latest/getting-started.html#setup](https://api-umbrella.readthedocs.io/en/latest/getting-started.html#setup).

**Comment by GUI** [comment]
v0.14.0 is released with a local login option, which should make this setup easier.
