### ISSUE TITLE
Cant get the index page

### ISSUE THREAD

**Issue by toktak** [NREL/api-umbrella#209]
Hi ,I have install api-umbrella on cent os 6 .My main dir refer to /var/www/html/DocumentRoot/ I cant get the admin page.It s there any conf file a part from /etc/api-umbrella/api-umbrella.yml.

**Comment by GUI** [comment]
@toktak: Sorry, but I'm not sure I understand your question. By default, API Umbrella will run on port 80 and 443 to server HTTP and HTTPS traffic directly by itself. What exactly are you trying to do with your content in `/var/www/html/DocumentRoot`? Are you trying to serve the content out of there for your home page, while just using API Umbrella for APIs? Are you also running Apache on this same server?
