### ISSUE TITLE
API Umbrella development environment

### ISSUE THREAD

**Issue by jykae** [NREL/api-umbrella#214]
I am trying to get development environment up and start learning the codebase.

I am getting error when Chef recipe runs. End of the stacktrace with errors below:
```
==> default: Running handlers:
==> default: [2016-01-29T12:57:21+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: 
==> default: [2016-01-29T12:57:21+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 14 resources updated in 01 minutes 59 seconds
==> default: [2016-01-29T12:57:21+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-01-29T12:57:21+00:00] ERROR: remote_file[/usr/local/src/phantomjs-1.9.8-linux-x86_64.tar.bz2] (phantomjs::source line 36) had an error: Chef::Exceptions::ContentLengthMismatch: Response body length 2062336 does not match HTTP Content-Length header 13163325.
==> default: [2016-01-29T12:57:21+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by jykae** [comment]
Ah, you run tests with nodejs.. ok

I didn't have environment variables set, I tried new run. Got a bit further.

Error in "make install":
```
==> default: Using built-in specs.
==> default: Target: x86_64-redhat-linux
==> default: Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
==> default: Thread model: posix
==> default: gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
Checking out files: 100% (353/353), done./353)   
==> default: make: *** [/vagrant/build/work/stage/.installed/api-umbrella-core-web-bundled] Error 5
==> default: ---- End output of make ----
==> default: Ran make returned 2
==> default: [2016-01-29T14:41:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by jykae** [comment]
Continued inside vagrant box.

Removed "-u" option from "build/package/scripts/after-install" line 8.
Caused unbound variable in Vagrant box.

Finally Umbrella 0.11.0 development installation now successfully running. :)

**Comment by jykae** [comment]
Made settings, and  but cannot access admin view.

Nginx logs:
--------------
2016-01-29T16:37:37.22272 2016/01/29 16:37:37 [error] 28169#0: [lua] elasticsearch_setup.lua:20: wait_for_elasticsearch(): failed to fetch cluster health from elasticsearch: connection refused, context: ngx.timer

**Comment by jykae** [comment]
* Another issue

Nginx logs:

2016-01-29T16:37:37.22272 2016/01/29 16:37:37 [error] 28169#0: [lua] elasticsearch_setup.lua:20: wait_for_elasticsearch(): failed to fetch cluster health from elasticsearch: connection refused, context: ngx.timer

**Comment by jykae** [comment]
Got logged in /admin but nothing works, Ember causes bunch of errors.

![embererror](https://cloud.githubusercontent.com/assets/293452/12685528/8bb3d3d0-c6cd-11e5-997b-80f3e5836a2c.png)

**Comment by jykae** [comment]
@GUI I would be happy to contribute on any issues if I would get development environment working. 
Help would be appreciated, thanks.

**Comment by GUI** [comment]
Sorry for the delay in following up and for the problems, but thanks for reporting them. I'm not sure off-hand what's leading to these different issues, but I'll try to take a look at these issues this week and make sure we get them resolved.

**Comment by jykae** [comment]
@GUI No problem, this is not so urgent, more like nice-to-have and happy-to-help :)

**Comment by GUI** [comment]
@jykae: Super sorry for the belatedness on this. I believe these various issues should be fixed in the latest vagrant development environment on master (I've repeatedly destroyed and created new development VMs several times in the past few weeks): https://api-umbrella.readthedocs.io/en/latest/developer/dev-setup.html

Please let us know if you continue to see any issues.
