### ISSUE TITLE
API Umbrella RPM package doesnt work on RHEL 7.2 and 7.1

### ISSUE THREAD

**Issue by rezadehganpour** [NREL/api-umbrella#215]
I try to install the new API umbrella following this guide http://apiumbrella.io/install/ on RHEL

I did install it successfully however when I try to go to the admin page, nginx is returning the 502 error.
<img width="1440" alt="screen shot 2016-02-05 at 6 46 18 pm" src="https://cloud.githubusercontent.com/assets/9387604/12862350/cb1238bc-cc38-11e5-914a-df8a5485e255.png">

and This is the opt/api-umbrella/var/log/nginx/access.log

`10.3.251.33 - - [05/Feb/2016:18:47:48 -0500] "GET /admin HTTP/1.1" 502 166 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0" aimfaq8duanu0tfg24r0 http://10.6.32.222:14012 0.000 -
10.3.251.33 - - [05/Feb/2016:18:47:48 -0500] "GET /admin HTTP/1.1" 502 166 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0" aimfaq8duanu0tfg24r0 https://10.6.32.222:443 0.000 MISS
10.3.251.33 - - [05/Feb/2016:18:47:51 -0500] "GET /admin HTTP/1.1" 502 166 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0" aimfaquocg7veilbjovg http://10.6.32.222:14012 0.000 -
10.3.251.33 - - [05/Feb/2016:18:47:51 -0500] "GET /admin HTTP/1.1" 502 166 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0" aimfaquocg7veilbjovg https://10.6.32.222:443 0.000 MISS
10.3.251.33 - - [05/Feb/2016:18:47:56 -0500] "GET / HTTP/1.1" 200 832 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0"  http://10.6.32.222:14013 0.000 -
10.3.251.33 - - [05/Feb/2016:18:47:56 -0500] "GET / HTTP/1.1" 200 832 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0" aimfas51vaog3ro7klmg https://10.6.32.222:443 0.001 MISS
10.3.251.33 - - [05/Feb/2016:18:47:56 -0500] "GET /assets/stylesheets/all-1a57c92c.css HTTP/1.1" 200 28998 "https://10.6.32.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0"  http://10.6.32.222:14013 0.000 -
10.3.251.33 - - [05/Feb/2016:18:47:56 -0500] "GET /assets/stylesheets/all-1a57c92c.css HTTP/1.1" 200 29052 "https://10.6.32.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0" aimfas69vlgujeov0sd0 https://10.6.32.222:443 0.014 MISS
10.3.251.33 - - [05/Feb/2016:18:47:56 -0500] "GET /assets/javascripts/all-ca6bc125.js HTTP/1.1" 200 38009 "https://10.6.32.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0"  http://10.6.32.222:14013 0.000 -
10.3.251.33 - - [05/Feb/2016:18:47:56 -0500] "GET /assets/javascripts/all-ca6bc125.js HTTP/1.1" 200 38079 "https://10.6.32.222/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0" aimfas72vto6o3brra4g https://10.6.32.222:443 0.002 MISS`

**Comment by GUI** [comment]
Can you post the contents of the `/var/log/api-umbrella/nginx/current` log file as well as the output from `sudo api-umbrella processes`? That should hopefully help pinpoint what might be going on.

**Comment by rezadehganpour** [comment]
in the nginx folder there is no `current` directory, just access.log and config. also when I run `sudo api-umbrella processes` the process doesnt five me anything it is just keep running.
but `sudo systemctl status api-umbrella`:
`api-umbrella.service - LSB: API Umbrella
   Loaded: loaded (/etc/rc.d/init.d/api-umbrella)
   Active: active (running) since Fri 2016-02-05 18:28:10 EST; 2 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9823 ExecStart=/etc/rc.d/init.d/api-umbrella start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/api-umbrella.service
           ├─ 9874 api-umbrella /opt/api-umbrella/etc/perp
           ├─ 9876 perpd /opt/api-umbrella/etc/perp
           ├─ 9882 bash /opt/api-umbrella/embedded/apps/core/current/bin/api-umbrella-geoip-auto-updater
           ├─ 9884 hekad -config=/opt/api-umbrella/etc/heka.toml
           ├─ 9886 mongod --config /opt/api-umbrella/etc/mongod.conf
           ├─ 9888 mora -config /opt/api-umbrella/etc/mora.properties
           ├─ 9890 nginx: master process nginx -p /opt/api-umbrella/embedded/apps/core/current/ -c /opt/api-umbrella/etc/nginx/router.conf
           ├─ 9892 bash /opt/api-umbrella/embedded/apps/core/current/bin/api-umbrella-nginx-reloader
           ├─ 9894 traffic_cop --stdout
           ├─ 9896 ruby ./script/delayed_job --pid-dir=/opt/api-umbrella/var/run --queues=mailers run
           ├─ 9927 /opt/api-umbrella/embedded/bin/traffic_manager
           ├─ 9972 nginx: worker process
           ├─ 9973 nginx: worker process
           ├─ 9974 nginx: worker process
           ├─ 9975 nginx: worker process
           ├─10055 /opt/api-umbrella/embedded/bin/traffic_server -M --httpport 14009:fd=7
           ├─12168 svlogd -ttt /opt/api-umbrella/var/log/trafficserver
           ├─12223 svlogd -ttt /opt/api-umbrella/var/log/nginx
           ├─12224 svlogd -ttt /opt/api-umbrella/var/log/mongod
           ├─12225 svlogd -ttt /opt/api-umbrella/var/log/web-delayed-job
           ├─12226 svlogd -ttt /opt/api-umbrella/var/log/web-puma
           ├─14568 perpctl -b /opt/api-umbrella/etc/perp hup nginx
           ├─17033 luajit /opt/api-umbrella/embedded/apps/core/current/bin/api-umbrella-cli reload
           ├─17072 sh -c perpctl -b /opt/api-umbrella/etc/perp term web-delayed-job 2>&1; echo "===STATUS_CODE:$?"
           └─17073 perpctl -b /opt/api-umbrella/etc/perp term web-delayed-job

Feb 08 11:07:13 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:14 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:15 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:16 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:17 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:18 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:19 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:20 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:21 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...
Feb 08 11:07:22 api-umbrella-app-07.east1a.dev api-umbrella[9823]: api-umbrella: warning: pausing for restart of ./rc.log ...`

**Comment by rezadehganpour** [comment]
@GUI So I I think I figure out the problem. it seems like that umbrella is depended on some out of country resources and our firewalls is blocking those.
I found http://www.lua.org and https://rails-assets.org,. is there any other resources that I need to know about?
