### ISSUE TITLE
Vagrant up or provision not complete

### ISSUE THREAD

**Issue by MustafaZain** [NREL/api-umbrella#218]
Hello All,

I face a problem that each time I run vagrant up it takes too much time in the compile step then make different errors like in the screenshot below also the http://10.10.33.2/ isn't working by anyway

![screenshot from 2016-02-11 16 32 56](https://cloud.githubusercontent.com/assets/10357250/12979007/1f8de35c-d0dd-11e5-9184-cdbffbe1c4d2.png)

![screenshot from 2016-02-11 15 01 44](https://cloud.githubusercontent.com/assets/10357250/12978995/09263b96-d0dd-11e5-8b20-e319c8af3c12.png)

**Comment by MustafaZain** [comment]
while accessing http://10.10.33.1/ I got

"Apache2 Ubuntu Default Page"

![screenshot from 2016-02-11 17 51 30](https://cloud.githubusercontent.com/assets/10357250/12981156/1c12f4be-d0e8-11e5-9e84-b9cf0003a0b9.png)

**Comment by jykae** [comment]
@MustafaZain Trying out development environment? I have opened issue for that as well, #214

**Comment by MustafaZain** [comment]
I got this error after reinstalling all packages again

`==> default: Installing nokogiri 1.6.7.2 with native extensions
==> default: --- ERROR REPORT TEMPLATE -------------------------------------------------------
==> default: - What did you do?
==> default: 
==> default:   I ran the command `/vagrant/build/work/stage/opt/api-umbrella/embedded/bin/bundle install --path=/vagrant/build/work/vendor/bundle`
==> default: 
==> default: - What did you expect to happen?
==> default: 
==> default:   I expected Bundler to...
==> default: 
==> default: - What happened instead?
==> default: 
==> default:   Instead, what actually happened was...
==> default: 
==> default: 
==> default: Error details
==> default: 
==> default:     SignalException: SIGTERM
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:64:in `join'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:64:in `each'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:64:in `stop_threads'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/worker.rb:41:in `stop'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/parallel_installer.rb:83:in `ensure in call'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/parallel_installer.rb:83:in `call'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer/parallel_installer.rb:63:in `call'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:170:in `install_in_parallel'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:155:in `install'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:70:in `run'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli/install.rb:105:in `run'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:172:in `install'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/lib/ruby/gems/2.2.0/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/bin/bundle:23:in `load'
==> default:       /vagrant/build/work/stage/opt/api-umbrella/embedded/bin/bundle:23:in `<main>'
==> default: 
==> default: Environment
==> default: 
==> default:     Bundler   1.11.2
==> default:     Rubygems  2.4.5.1
==> default:     Ruby      2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
==> default:     GEM_HOME  /vagrant/build/work/vendor/bundle/ruby/2.2.0
==> default:     GEM_PATH  
==> default:     Git       2.7.0
==> default: 
==> default: Bundler settings
==> default: 
==> default:     path
==> default:       Set for your local app (/vagrant/src/api-umbrella/web-app/.bundle/config): "/vagrant/build/work/vendor/bundle"
==> default:     disable_shared_gems
==> default:       Set for your local app (/vagrant/src/api-umbrella/web-app/.bundle/config): "1"
==> default: --- TEMPLATE END ----------------------------------------------------------------
==> default: 
==> default: Unfortunately, an unexpected error occurred, and Bundler cannot continue.
==> default: 
==> default: First, try this link to see if there are any existing issue reports for this error:
==> default: https://github.com/bundler/bundler/search?q=SIGTERM&type=Issues
==> default: 
==> default: If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
==> default: https://github.com/bundler/bundler/issues/new
==> default: STDERR: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> default:                                  Dload  Upload   Total   Spent    Left  Speed
100 12.7M  100 12.7M    0     0   201k      0  0:01:04  0:01:04 --:--:--  209k
==> default: Using built-in specs.
==> default: Target: x86_64-redhat-linux
==> default: Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
==> default: Thread model: posix
==> default: gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
==> default: eval.c: In function ‘setup_exception’:
==> default: eval.c:537: warning: ‘_th’ may be used uninitialized in this function
==> default: eval.c: In function ‘ruby_setup’:
==> default: eval.c:56: warning: ‘_th’ may be used uninitialized in this function
==> default: eval.c: In function ‘ruby_options’:
==> default: eval.c:98: warning: ‘_th’ may be used uninitialized in this function
==> default: In file included from eval.c:30:
==> default: eval_jump.c: In function ‘rb_exec_end_proc’:
==> default: eval_jump.c:119: warning: ‘_th’ may be used uninitialized in this function
==> default: eval_jump.c:116: warning: ‘th’ may be used uninitialized in this function
==> default: eval.c: In function ‘ruby_cleanup’:
==> default: eval.c:175: warning: ‘_th’ may be used uninitialized in this function
==> default: eval.c:185: warning: ‘_th’ may be used uninitialized in this function
==> default: eval.c:165: warning: ‘_th’ may be used uninitialized in this function
==> default: load.c: In function ‘rb_load_internal0’:
==> default: load.c:602: warning: ‘_th’ may be used uninitialized in this function
==> default: proc.c: In function ‘rb_method_call_with_block’:
==> default: proc.c:1864: warning: ‘_th’ may be used uninitialized in this function
==> default: proc.c:1856: warning: ‘data’ may be used uninitialized in this function
==> default: In file included from sprintf.c:1258:
==> default: vsnprintf.c: In function ‘BSD_vfprintf’:
==> default: vsnprintf.c:822: warning: comparison of unsigned expression < 0 is always false
==> default: string.c: In function ‘rb_fstring_new’:
==> default: string.c:270: warning: dereferencing pointer ‘fake_str.60’ does break strict-aliasing rules
==> default: string.c:270: note: initialized from here
==> default: In file included from vm.c:102:
==> default: vm_eval.c: In function ‘rb_iterate’:
==> default: vm_eval.c:1118: warning: ‘_th’ may be used uninitialized in this function
==> default: vm_eval.c:1113: warning: ‘node’ may be used uninitialized in this function
==> default: vm_eval.c:1114: warning: ‘th’ may be used uninitialized in this function
==> default: vm_eval.c: In function ‘eval_string_with_cref’:
==> default: vm_eval.c:1257: warning: ‘_th’ may be used uninitialized in this function
==> default: vm_eval.c: In function ‘rb_eval_cmd’:
==> default: vm_eval.c:1544: warning: ‘_th’ may be used uninitialized in this function
==> default: vm_eval.c:1529: warning: ‘_th’ may be used uninitialized in this function
==> default: vm_backtrace.c: In function ‘rb_debug_inspector_open’:
==> default: vm_backtrace.c:1184: warning: ‘_th’ may be used uninitialized in this function
==> default: vm_trace.c: In function ‘rb_suppress_tracing’:
==> default: vm_trace.c:406: warning: ‘_th’ may be used uninitialized in this function
==> default: vm_trace.c: In function ‘exec_hooks_protected’:
==> default: vm_trace.c:297: warning: ‘_th’ may be used uninitialized in this function
==> default: thread.c: In function ‘exec_recursive’:
==> default: thread.c:4879: warning: ‘_th’ may be used uninitialized in this function
==> default: thread.c:4845: warning: ‘sym’ may be used uninitialized in this function
==> default: thread.c: In function ‘thread_start_func_2’:
==> default: thread.c:575: warning: ‘_th’ may be used uninitialized in this function
==> default: thread.c: In function ‘rb_thread_s_handle_interrupt’:
==> default: thread.c:1806: warning: ‘_th’ may be used uninitialized in this function
==> default: thread.c: In function ‘rb_thread_terminate_all’:
==> default: thread.c:483: warning: ‘_th’ may be used uninitialized in this function
==> default: cont.c: In function ‘cont_capture’:
==> default: cont.c:483: warning: ‘cont’ may be used uninitialized in this function
==> default: Using built-in specs.
==> default: Target: x86_64-redhat-linux
==> default: Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
==> default: Thread model: posix
==> default: gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
Checking out files:  24% (85/353)   % (13/353)   
Checking out files: 100% (353/353), done.
Checking out files: 100% (34/34), done.14/34)   
==> default: make: *** [/vagrant/build/work/stage/.installed/api-umbrella-core-web-bundled] Terminated
==> default: ---- End output of make ----
==> default: Ran make returned 
==> default: [2016-02-11T19:16:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.`


![screenshot from 2016-02-11 21 29 18](https://cloud.githubusercontent.com/assets/10357250/12987819/87741080-d106-11e5-8284-a89f94c23d95.png)

**Comment by MustafaZain** [comment]
The error now is

`/vagrant/build/work/stage/.installed/api-umbrella-core-web-bundled] Error 5`

`An error occurred while installing rails_config (0.4.2), and Bundler cannot
==> default: continue.
==> default: Make sure that gem install rails_config -v '0.4.2' succeeds before bundling.
==> default: STDERR: make: *** [/vagrant/build/work/stage/.installed/api-umbrella-core-web-bundled] Error 5
==> default: ---- End output of make ----
`

**Comment by GUI** [comment]
@MustafaZain: I'm very sorry this slipped by us earlier. I'm not entirely sure what was going on with the earlier errors you encountered, but if you'd like to try setting up a new [development environment](https://api-umbrella.readthedocs.io/en/latest/developer/dev-setup.html), we've fixed several issues with the vagrant setup in API Umbrella's latest `master`. Please let us know if you're still seeing any issues.

**Comment by MustafaZain** [comment]
No need It's OK now
