### ISSUE TITLE
Your API Site Name & Website backends

### ISSUE THREAD

**Issue by mitchellfranklin** [NREL/api-umbrella#222]
Hi All, Been looking and looking but cant find any information on this so forgive me if I have missed it.

After install and setting up an API what are the steps required to change the main screen users see to add in the API name, doco etc? i though it may be under website backends but does not look the case.

Also on website backends - what is this used for? if it is used for the above could I please be pointed in the direction of the doco?
- one minor question, does api umbrella support testing for the user on the api i.e. select post and provide the information to see the return?\

Thanks

Mitch

**Comment by brylie** [comment]
@mitchellfranklin see issue #69 for a description of how to change the index page.

**Comment by brylie** [comment]
We ended up using [Swagger UI](http://swagger.io/swagger-ui/) in a [custom API Umbrella integrated application](https://github.com/apinf/api-umbrella-dashboard) to support user API testing - as well as to implement features such as custom branding, etc.

**Comment by GUI** [comment]
Well, very belated, but here's some additional docs I finally put together to try to clarify how website backends work: https://api-umbrella.readthedocs.io/en/latest/admin/website-backends.html

Hopefully that helps, but there's probably still more we need to flush out, so give a shout if anything's unclear or you have any further questions.
