### ISSUE TITLE
Umbrella 0.11 Mongo warnings

### ISSUE THREAD

**Issue by jykae** [NREL/api-umbrella#224]
Mongo is giving warnings:
```
2016-03-07T13:44:45.903+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2016-03-07T13:44:45.903+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2016-03-07T13:44:45.903+0000 I CONTROL  [initandlisten] 
2016-03-07T13:44:45.903+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2016-03-07T13:44:45.903+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
```
There is script available on MongoDB to fixing this, https://docs.mongodb.org/manual/tutorial/transparent-huge-pages/

Or is there reason why those are set to "always" ?

**Comment by GUI** [comment]
These are system-level kernel defaults, so the default `always` values are coming from the your linux distro. If you want to adjust these, you'll need to take the recommended steps in the mongo guide to change these for the entire system. But be aware that these recommendations are for dedicated MongoDB servers. If you're running MongoDB on the same server as your API Umbrella proxy server (the default setup, unless you've explicitly split things up), then these changes may not be as appropriate for the rest of the software stack (they may be fine, it's just not something I've researched).

Although, if it's just API Umbrella making use of the MongoDB database, the data stored in mongo is quite small, and we don't put a lot of strain on MongoDB, so these settings probably don't matter a great deal (we've never seen issues in our servers with the default values that generate these warnings, so I've never really bothered to investigate further).

**Comment by GUI** [comment]
Going to go ahead and close this, since this is more of a system-level tuning issue (and not something we can address directly in API Umbrella's code base). Let us know if you have any other questions.
