### ISSUE TITLE
Update Docker image to include latest release

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#228]
The [NREL API Umbrella docker image](https://hub.docker.com/r/nrel/api-umbrella/) has not been updated in over 4 months. Please update the Docker image with the latest API Umbrella release.

**Comment by brylie** [comment]
@GUI any status update on the plans for NREL/API-Umbrella Docker image?

**Comment by shaliko** [comment]
@GUI ping

**Comment by GUI** [comment]
A docker image of the latest v0.11.1 release made today is now available: https://hub.docker.com/r/nrel/api-umbrella/tags/

I'll try to ensure building docker images is part of our normal packaging release process moving forward.

**Comment by brylie** [comment]
@GUI, in case it is helpful, Dockerhub has [automated build instructions](https://docs.docker.com/docker-hub/builds/).
