### ISSUE TITLE
Open GPG key for trusty package

### ISSUE THREAD

**Issue by ThibautGery** [NREL/api-umbrella#232]
I'm looking to add the package GPG key to install umbrella with Ansible
I've tried to add [this key](https://bintray.com/nrel/api-umbrella-ubuntu/download_file?file_path=dists%2Ftrusty%2FRelease.gpg) with `apt-key add` to my server but I have this error `gpg: no valid OpenPGP data found.`

Does the key exist ?

**Comment by GUI** [comment]
Unfortunately I don't think the packages are properly signed with any key. We have an open issue for that: https://github.com/NREL/api-umbrella/issues/197

As a stop-gap, here are the SHA256 checksums if you'd like to manually verify any downloaded packages: https://github.com/NREL/api-umbrella/blob/master/sha256sums.txt However, I realize this isn't really a replacement for GPG signing and apt/yum integration. We're definitely interested in addressing that (hopefully in the next release).

**Comment by ThibautGery** [comment]
Thank you. I will allow insecure installation the time being.
