### ISSUE TITLE
Disable SSLv3 (POODLE)

### ISSUE THREAD

**Issue by jykae** [NREL/api-umbrella#234]
We are getting mail from our server host about security checks for POODLE.

Could we disable SSLv3 by default in Umbrella nginx ?

http://disablessl3.com/

**Comment by jykae** [comment]
Ran SSL Labs tests for our Umbrella instances, 0.11 seems to have this fixed, but 0.8 has this issue, so upgrading probably fixes the issue.

**Comment by GUI** [comment]
Sorry for the delay in responding. Going to close, since this was fixed in v0.11, and there will be further SSL improvements in the upcoming v0.12 release (https://github.com/NREL/api-umbrella/pull/240).
