### ISSUE TITLE
Enabling proxy_cache prevents dyups initialization

### ISSUE THREAD

**Issue by noobfoot** [NREL/api-umbrella#235]
I'm trying to see if I can cache some content at the nginx level by configuring the proxy_cache directives.  But whenever I enable them, the dynamic upstreams seem to be returning a 405 status with a "API disabled" message.  I've basically uncommented out the directives that were already in API Umbrella's router.conf.mustache file:

proxy_cache_path /tmp/nginx-cache levels=1:2 keys_zone=backcache:8m max_size=50m;
proxy_cache backcache;
proxy_cache_valid 5m;

Any particular reason why the cache directives are commented out?  Maybe you guys ran into the issue i'm dealing with?

Could this issue be because of the ngx_http_dyups_module team's comment?
https://github.com/yzprofile/ngx_http_dyups_module/issues/48

> It's better not call update/delete API in init_worker, the dyups module will sync the change to other workers automatically.

**Comment by GUI** [comment]
There's already a caching layer in place, provided by TrafficServer (rather than nginx's caching). It can be leveraged if your APIs return any of the standard cache control headers: http://api-umbrella.readthedocs.io/en/latest/admin/api-backends/caching.html

Is there a reason you were looking to use nginx's cache, or does the TrafficServer cache suite your needs? We had experimented with nginx's caching a while ago, but if I recall correctly, the main issue was that it breaks when `proxy_buffering` is on (and turning that off is more important to us, since that allows for streaming large responses). I forget how exactly it broke when proxy_buffering was off, but that may also be playing a role in the errors you're seeing. In general, though, Traffic Server should provide a more robust caching layer.

Sorry for any confusion those commented out nginx config lines caused, but thanks for pointing them out. I will remove those, since those were just left over from our earlier experiments that didn't pan out.

**Comment by noobfoot** [comment]
Ah, thank you for pointing the TrafficServer out!  I'll give that a shot and see if it suffices for my use case.

The main reason I was looking into nginx's cache was because its already there, built into nginx.  And also because I could fine tune my caching thru its directives. 

Totally agree with you on allowing streaming API responses being a priority.  The proxy_buffering hadn't even come up in my debugging.  I was looking into [ngx_http_dyups_module's](https://github.com/yzprofile/ngx_http_dyups_module/blob/master/ngx_http_dyups_module.c) source code to determine where those 405 responses were coming from.  It seems to be stemming from  a flag that is set on startup:

    if (!dmcf || !dmcf->enable || ngx_process == NGX_PROCESS_HELPER) {
        ngx_http_dyups_api_enable = 0;
        return NGX_OK;
    }

    ngx_http_dyups_api_enable = 1;

and later referrenced when updating the upstreams:

    if (!ngx_http_dyups_api_enable) {
        ngx_str_set(rv, "API disabled\n");
        return NGX_HTTP_NOT_ALLOWED;
    }

No worries on the leftovers.  I've been know to do the same :)

**Comment by noobfoot** [comment]
ok, so here is my use case:  I would like to authenticate users based on their PKI prior to allowing them thru to an API.  The DN taken from the PKI certificate is forwarded to an authentication daemon and an answer is received whether to let the user continue or not.  I'm referring to the following pattern described by NGINX [here](https://www.nginx.com/blog/nginx-plus-authenticate-users/).

I've update the router.conf.mustache at the default server to turn on two-way ssl with this, which is working (on port 443 of course):

```
ssl_client_certificate /path/to/cert.pem;
ssl_trusted_certificate /path/to/trusted_cert.pem;
ssl_certificate /path/to/cert.pem;
ssl_certificate_key /path/to/key.pem;
ssl_verify_client on;
ssl_verify_depth 3;
```

I've also added an internal location for a gatekeeper validator to ask for an authentication response:

```
location = /auth-proxy {
     internal;
     proxy_http_version 1.1;
     proxy_set_header Connection "";
     proxy_pass http://authenticator_upstream;  
}
```

Also defined the upstream:

```
upstream authenticator_upstream {
  server 127.0.0.1:8888;
  keepalive 10; 
}
```

And added another validator in the gatekeeper which does some checks and passes the client DN in a header to the auth-proxy. I could use NGINX's [ngx_http_auth_request_module](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html?_ga=1.90048347.1300442093.1461778585) but it is not compiled into API-Umbrella's NGINX (an OpenResty version I believe). Here's the main snippet:
```
local res = ngx.location.capture("/auth-proxy")
if res.status == ngx.HTTP_OK then
  return user
end
return nil, "user_forbidden"
```

The daemon running on port 8888 uses a policy decision point's restful API.  My obstacle at the moment is to cache the responses of the auth-proxy location so that the daemon does not get hit quite often.  This is what lead me to try NGINX's cache but that's not working due to GUI's comments.
I should mention that everything is working except the caching.  How would I go about integrating the traffic server's cache into my workflow?  Thank you in advance for your suggestions :)

**Comment by noobfoot** [comment]
I was able to place my authentication daemon behind API Umbrella's TrafficServer and those requests are going thru without a problem.  However I am getting cache misses all the time.

This is what TrafficServer is returning in the `Via `header:

> http/1.1 0b58fc352549 (ApacheTrafficServer [cMsSf ])

Which based on TrafficServer's documentation means the following:

> miss (a cache "MISS")
> served
> no cache write performed

In my authenticating daemon I am setting the Cache-Control and Vary headers.  The latter because per TrafficServer's documentation about requests with the [same URL](http://trafficserver.readthedocs.io/en/latest/admin-guide/configuration/cache-basics.en.html#caching-http-alternates) (alternates), which are how my authenticating requests are being done.
