### ISSUE TITLE
The Architecture diagram is not correct anymore

### ISSUE THREAD

**Issue by ThibautGery** [NREL/api-umbrella#249]
http://api-umbrella.readthedocs.io/en/latest/developer/architecture.html

**Comment by GUI** [comment]
Thanks for spotting that. We'll look to get that updated.

**Comment by GUI** [comment]
Thanks again for finding this. This should be [fixed](https://github.com/NREL/api-umbrella/commit/c5960dcd516b2ea4fd2350a813b3352908ea5374) now: http://api-umbrella.readthedocs.io/en/latest/developer/architecture.html
