### ISSUE TITLE
Binary Package for MAC

### ISSUE THREAD

**Issue by vicky-fd** [NREL/api-umbrella#255]
I am finding it difficult to setup and run this on MAC OSX EL CAPITON

**Comment by GUI** [comment]
API Umbrella is currently only compatible with Linux. What purpose were you looking to run API Umbrella on your Mac for? Would it be to just try it out/demo it, or would it be for development purposes, or would the Mac your server?

There are a few virtualized options to run it on your Mac, though:

- Create a Linux virtual machine, and [instal](https://apiumbrella.io/install/)l one of the Linux binaries into the virtual machine.
  - Similarly, we provide a [Vagrant development environment](https://api-umbrella.readthedocs.io/en/latest/developer/dev-setup.html) that uses a Linux virtual machine environment, but is geared towards API Umbrella development.
- If you run Docker on your Mac, then you can also run API Umbrella [via Docker](https://api-umbrella.readthedocs.io/en/latest/getting-started.html#running-with-docker).

If you were looking for a non-virtualized option for the Mac, then we don't currently support that. I believe it should technically be possible, it's just that we have a variety of things in our build process that are currently hard-coded for the assumption we're running under Linux. So those build assumptions would need to be updated to account for building on the Mac. We don't have any plans to make those changes ourselves, but we'd welcome any pull requests that added direct Mac compatibility to the build process.
