### ISSUE TITLE
Make installation process easier and quicker

### ISSUE THREAD

**Issue by GUI** [NREL/api-umbrella#26]
The process for installing API Umbrella could use some improvement, to make it easier and quicker. The general plan is to offer self-contained RPMs and debs, so we have simple one-click installers for installing API Umbrella and all of it's dependencies.

Work has already started on this in the [omnibus-api-umbrella](https://github.com/NREL/omnibus-api-umbrella). This uses the [omnibus](https://github.com/opscode/omnibus-ruby) packaging system the opscode folks came up with to easily create self-contained package installers across different OSes. The package installer will install all the dependencies, and then there's some initial work on the [config branch](https://github.com/NREL/api-umbrella-router/tree/config) to introduce a single command line utility, `api-umbrella-ctl` that will run all the necessary dependencies on demand. The general idea is that once this work is done, running API Umbrella will be as simple as installing a package for your OS and then running something like `api-umbrella-ctl start`.

For a bit of background on why this has become an issue: the basic issue right now is that the installation process has become quite dependent on our custom Chef scripts. The main problems with this are that it requires users to use Chef (which obviously not everyone uses), they must use some of our custom Chef cookbooks (and how we need something like nginx configured may not jive with how someone else wants to install nginx on other systems Chef manages), and our cookbooks only target RHEL/CentOS 6. So while we can automate this for development purposes using our Vagrant setup, it's not ideal for people wanting to deploy this to different types of production environments. Plus, all of these changes should also make the Vagrant setup process go much faster, since everything will come bundled in the binary package installers.

Docker could also be a good candidate for simplifying this kind of thing, but that also places a dependency on Docker that I don't quite want to mandate (because again, not everyone uses it). However, we could certainly offer Docker images of API Umbrella in addition to the packages pretty easily once once we get all this sorted out.

**Comment by brylie** [comment]
There is a [pull request open with a Dockerfile](https://github.com/NREL/api-umbrella/pull/178).
