### ISSUE TITLE
Custom Omniauth Strategy Not Loading

### ISSUE THREAD

**Issue by noobfoot** [NREL/api-umbrella#267]
I'm trying to use a custom Omniauth Strategy I created that calls my company's internal authentication restful API.  Its very basic at the moment, but the current issue i'm having is getting Omniauth to pick it up. 

This is what I've done so far:
- I followed the [Omniauth's developer guide](https://github.com/intridea/omniauth/wiki/Strategy-Contribution-Guide) to create my strategy.  I placed it along with some of the bundled strategies at:
/opt/api-umbrella/embedded apps/core/shared/vendor/bundle/ruby/2.2.0/bundler/gems/omniauth-iab-0.0.1/
- I also included it in api-umbrella web-app's Gemfile:
gem "omniauth-iab", :path => "/opt/api-umbrella/embedded apps/core/shared/vendor/bundle/ruby/2.2.0/bundler/gems/omniauth-iab-0.0.1/"
- I also updated the api-umbrella.yml file to use my strategy:
```
   auth_strategies:
     enabled:
       - iab
     iab:
       options:
         op1: 'op1 value'
```
- I also updated the devise.rb in the webapp's config/initializers folder:
```
   ...
   when "iab"
     config.omniauth :iab
   else
   ...
```

Thank you in advance for your comments.

**Comment by GUI** [comment]
What exactly is happening? Are you getting any errors, or it simply not showing up as a login option?

**Comment by noobfoot** [comment]
The exact error in the web-puma logs was:

> 'autoload_strategy': Could not find a strategy with name 'Iab'. Please ensure it is required or explicitly set in using the :strategy_class option. (Devise::OmniAuth::StrategyNotFound)

I was able to get it loaded by adding the following to my .gemspec file:
`$.push File.expand_path("../lib", __FILE__)`

Its being picked up now :)
