### ISSUE TITLE
Add Custom Header

### ISSUE THREAD

**Issue by rogeriollacerda** [NREL/api-umbrella#268]
Hi,

How is the best way to add a custom response header in Nginx router or gate keeper? Can I use api-umbrella.yml? Can I use any Nginx parameter in that file as I've using in commom nginx.conf?

Tks!

**Comment by rogeriollacerda** [comment]
Hi, I found how set header. I used mustache template file.

Tks!

**Comment by GUI** [comment]
Glad you found it. For anyone else's reference, in the API Backends form, under "Global Request Settings" there are two options, "Default Response Headers" and "Override Response Headers" that can set custom response headers. The tooltip help on those fields provides some additional documentation on their differences.
