### ISSUE TITLE
REST interface for analytics drilldown responds with 500 error code.

### ISSUE THREAD

**Issue by frenchbread** [NREL/api-umbrella#275]
### Not possible to fetch analytics drilldown data from api-umbrella instance:

`GET` **`https://<api-umbrella-domain>/api-umbrella/v1/analytics/drilldown`** request responds with 500 error code.

---
For example `GET` **`https://<api-umbrella-domain>/api-umbrella/v1/admins`**  works just fine.

`X-Admin-Auth-Token` & `X-Api-Key` headers were provided and are correct.

(Requests tested via POSTMAN)

**Comment by GUI** [comment]
I think this can happen if you don't pass in one of the required fields, or if the `prefix` parameter isn't in the right format. But we obviously need to do some better parameter validation on this API, so it provides better feedback rather than throwing a 500 error.

In the meantime, here's an example of a valid initial request request starting at the root:

```
/api-umbrella/v1/analytics/drilldown.json?interval=day&start_at=2016-07-04&end_at=2016-08-02&prefix=0%2F
```

Note `prefix` is `0/` (it must contain a slash). Once you get the root response, you can use the `descendent_prefix` field in the response to generate further `prefix` parameters to drill down into the results.

**Comment by frenchbread** [comment]
Thanks @GUI! It works fine when fields are passed.

**Comment by frenchbread** [comment]
Also, how is it possible to filter by API backend `frontend_prefix` value using URL above? I've tried a lot of different ways passing elasticsearch query as a `search` parameter but it did not work. Could you please provide a sample URL which does that?

**Comment by GUI** [comment]
@frenchbread: You'd filter by the `request_path` field. You can filter using the `search` URL parameter if you want to pass in a raw Lucene-style query, or by the `query` URL parameter if you want to use the [query-builder](http://querybuilder.js.org) JSON format the default admin tool uses. Here are a couple examples that filter for API traffic beginning with `/foo/` (if you url-decode these, the examples will probably make more sense):

Using `search` (note that with the Lucene syntax forward slashes need to be escaped with backslashes):
```
/api-umbrella/v1/analytics/drilldown.json?interval=day&start_at=2016-07-04&end_at=2016-08-02&prefix=0%2F&search=request_path%3A%5C%2Ffoo%5C%2F*
```

Using `query` with a JSON format:
```
/api-umbrella/v1/analytics/drilldown.json?interval=day&start_at=2016-07-04&end_at=2016-08-02&prefix=0%2F&query=%7B%22condition%22%3A%22AND%22%2C%22rules%22%3A%5B%7B%22id%22%3A%22request_path%22%2C%22field%22%3A%22request_path%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22text%22%2C%22operator%22%3A%22begins_with%22%2C%22value%22%3A%22%2Ffoo%2F%22%7D%5D%7D
```

Hope that helps, but feel free to ask if you still have any other questions.

**Comment by marla-singer** [comment]
Hey, @GUI. I'd like to ask about `query` URL parameter. Try to use your example and I've got 500 error. Although, without this parameter everything is okay.
Could you please tell the right structure of `query` body?

**Comment by GUI** [comment]
@marla-singer: The `query` parameter takes URL-encoded JSON, with the structure coming from [jQuery QueryBuilder's rules](http://querybuilder.js.org/#method-getRules).

Although, the example `query` above still works for me, so if it's throwing a 500 error for you, I'm not entirely sure what's going on. You might try seeing what's in the `/var/log/api-umbrella/web-puma/current` log. If you can share any errors from there, then hopefully we can get to the bottom of the 500 error.

**Comment by marla-singer** [comment]
Thanks for your answer! I tested the example again and it worked as expected. There was my fault
