### ISSUE TITLE
Configuring Elasticsearch with SSL

### ISSUE THREAD

**Issue by shaliko** [NREL/api-umbrella#279]
Is it possible configure Elasticsearch working with SSL (https://some_domain:14002)? 

I not found option for configure in file "[api-umbrella/templates/etc/elasticsearch/logging.yml.mustache](https://github.com/NREL/api-umbrella/blob/master/templates/etc/elasticsearch/logging.yml.mustache)"

**Comment by GUI** [comment]
If you're running your own elasticsearch cluster with HTTPS already configured, then it should work if you point the [configuration](https://api-umbrella.readthedocs.io/en/latest/server/multi-server.html#database-configuration) to https URLs.

However, if you're using the built-in elasticsearch instance API Umbrella bundles, then no, it does not currently support HTTPS. To support that, I believe we'd have to put something like nginx or Shield in front of Elasticsearch. We probably don't have any plans to support that ourselves, but any pull requests adding that as an option would be gladly accepted.

**Comment by shaliko** [comment]
@GUI Thanks for clarification!
