### ISSUE TITLE
Docker image for 0.13.0 (2016-07-30) version 

### ISSUE THREAD

**Issue by shaliko** [NREL/api-umbrella#283]
@GUI Can you team create and share on docker hub image for 0.13.0 (2016-07-30) version ?

Thanks!

**Comment by GUI** [comment]
Oops, very sorry we missed this! Thanks for letting us know. We'll try to get the v0.13 image published sometime in the next few days.

**Comment by GUI** [comment]
The docker image for v0.13.0 has been published. Thanks again for brining this up!
