### ISSUE TITLE
Ubuntu 14.04 install fail, access denied

### ISSUE THREAD

**Issue by g-borgulya** [NREL/api-umbrella#285]
Trying to follow the installer instructions, but:

```bash
$ sudo apt-get install api-umbrella
...
E: Failed to fetch https://dl.bintray.com/nrel/api-umbrella-ubuntu/pool/main/a/api-umbrella/api-umbrella_0.13.0-1~trusty_amd64.deb  HttpError401
```

**Comment by GUI** [comment]
Very strange, sorry for the trouble, but thanks for bringing this to our attention. It looks like some of the v0.13 packages got published, but not all. We'll try to re-upload (but it unfortunately might be a few days).

**Comment by GUI** [comment]
This should be fixed now. Thanks again for letting us know!
