### ISSUE TITLE
API Umbrella Admin API documentation not rendering properly

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#289]
When reading the [Admin API documentation on readthedocs](https://api-umbrella.readthedocs.io/en/latest/admin/api.html), the inline Swagger UI is cutting off parts of the Model documentation, with no possibility to scroll right:

![screenshot from 2016-08-29 13-35-15](https://cloud.githubusercontent.com/assets/17307/18048915/b722769e-6ded-11e6-8aa6-1616a68a0f72.png)

This makes it difficult to figure out what fields are required, and other relevant details.

**Comment by GUI** [comment]
You should now be able to horizontal scroll in those docs. They layout isn't great, but it was the simplest solution to at lest make them viewable for now. But thanks for letting us know!

**Comment by brylie** [comment]
OK, thanks. I can't figure out how to horizontally scroll in Firefox. Should there be a scrollbar somewhere?

**Comment by GUI** [comment]
Hm, are you on OS X? If so, I know Firefox [now uses](http://stackoverflow.com/questions/18317634/force-visible-scrollbar-in-firefox-on-mac-os-x) the standard OS X behavior of making scrollbars invisible until you actually start scrolling (which is a bit maddening from a discoverability perspective, but it seems to be how OS X rolls these days). So to scroll, I think you have to use something like two finger horizontal scrolling on a trackpad of magic mouse. Or alternatively, you can [force OS X to always show scrollbars](http://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/).

If you're not on OS X, then I'm not too sure, unless other systems are now taking on the same auto-hiding behavior. Assuming scrollbars are visible, there should be a scrollbar at the bottom of each section that's too wide:

<img width="734" alt="screen shot 2016-09-02 at 6 49 38 am" src="https://cloud.githubusercontent.com/assets/12112/18204348/8147588e-70d9-11e6-9c3a-f3769acb7295.png">

The only other weird workaround I can think of is to click and drag on the text to start selecting it. As you select more text to the right, I think it should automatically scroll into view (even if scrollbars are hidden).

Sorry for the oddities. We'll have to see about revisiting this layout at some point.

**Comment by brylie** [comment]
Nevermind, sorry. It works here in Brave, Chromium, and Firefox on Linux. The styling of the bar may have made it less than easy for me to see, but it was still user error.
