### ISSUE TITLE
Multiserver Document Clarification

### ISSUE THREAD

**Issue by djphan** [NREL/api-umbrella#294]
Hi,

I'm investigating the use of Umbrella API on a multi server setup. I followed the docs per: http://api-umbrella.readthedocs.io/en/latest/server/multi-server.html and observed that:
1. When I only configure the changes in the .yml file the application web UI breaks and 
2. Through some help the replica set for the MongoDB is not created through the yml file.

I was able to solve my issue by initializing and creating the replica set manually in Mongo to conform to the standards listed on the doc.

I was wondering if this is expected (to manually configure Mongo) or did I miss a step in this setup that API-Umbrella should handle?

Thanks!

**Comment by GUI** [comment]
Sorry for the belated response. But what you did sounds correct--you'll still need to do the normal Mongo replica set procedure. I've updated the docs to hopefully clarify this and link to the more detailed MongoDB docs on this procedure.
