### ISSUE TITLE
Turning off HTTPs in API-Umbrella

### ISSUE THREAD

**Issue by djphan** [NREL/api-umbrella#296]
Hi, 

Just curious with this doc on HTTPs configs: http://api-umbrella.readthedocs.io/en/latest/server/https-config.html and this old issue chain: https://github.com/NREL/api-umbrella/issues/112

It was mentioned that for: 

> SSL Termination: If you’re placing API Umbrella behind a load balancer in a multi-server setup, you can handle the SSL termination with that external load balancer

I was wondering if there was a way to turn off HTTPs/SSL checking in the .yml file. I have a similar setup with a load balancer in front of API-Umbrella where I'd like to handle SSL termination there. But it is unclear to the details on how you're doing so there when the default API-Umbrella has its own self signed certificates.

Thanks

**Comment by GUI** [comment]
Sorry for the delay. We've added some additional documentation about SSL termination in a couple places:

https://api-umbrella.readthedocs.io/en/latest/server/https-config.html
https://api-umbrella.readthedocs.io/en/latest/server/listen-ports.html

Generally speaking, you should be able to perform SSL termination, and things should just work as long as your SSL terminator sends back `X-Fowarded-Proto` and `X-Forwarded-Port` headers. I know Amazon ELBs do this by default, and we use ELBs for SSL termination in some of our uses. But let us know if that doesn't answer your question, or you're still having any issues.
