### ISSUE TITLE
Add retrieving repository key to install instructions

### ISSUE THREAD

**Issue by bzar** [NREL/api-umbrella#299]
Current install instructions at https://apiumbrella.io/install/ result in an error (Ubuntu 16.04) at apt-get update because the repository key is not imported. This can be fixed with

    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61

**Comment by GUI** [comment]
Sorry for the very delayed response, but this was taken care of in https://github.com/NREL/api-umbrella/pull/353. Thanks for the suggestion!
