### ISSUE TITLE
Authorization with API Umbrella

### ISSUE THREAD

**Issue by anshulbhargava** [NREL/api-umbrella#301]
Hi,
      I was wondering if user role authorization ( something like ACL ) is available with API Umbrella. I looked up the available docs and found that there is a field called required roles ( in API setup ). But I don't think it does what I am looking for. I would wanna setup roles such as admin, developer, etc so that if an admin makes a request to an API that is developer-only, he should get something like "Unauthorized Access". Is any such option available ?

**Comment by GUI** [comment]
I think the "roles" feature should accomplish this (if an API key doesn't have all of the required roles, then the request will be rejected). I just added a new documentation page that explains how the role system work in a bit more detail: https://api-umbrella.readthedocs.io/en/latest/admin/api-backends/role-restrictions.html But let us know if you still have any questions, or this doesn't meet your needs.

**Comment by GUI** [comment]
Closing this issue, but let us know if you still have any questions.
