### ISSUE TITLE
API backend usage/permissions based on API keys

### ISSUE THREAD

**Issue by alfredjkwak** [NREL/api-umbrella#302]
@GUI Is it possible to make API keys to have access just specified API backend(s) OR define users/API keys that are allowed to use API backend?

In case of misuse we could revoke usage permissions for that user/API key for API backend, and it would only effect for that single API backend.

Also how is "api key verification level" setting meant to be used?
https://github.com/NREL/api-umbrella/blob/3f90e1589619bc4f893c1aaafe26bacd78a1a48a/src/api-umbrella/proxy/middleware/api_key_validator.lua

**Comment by GUI** [comment]
@jykae: I think perhaps the "roles" feature is what you're looking for. I've just added some additional documentation explaining this in more detail: https://api-umbrella.readthedocs.io/en/latest/admin/api-backends/role-restrictions.html Let us know if you still have any questions or that's not what you're looking for.

**Comment by GUI** [comment]
Closing this issue, but let us know if you have any further questions.
