### ISSUE TITLE
OAuth redirect URL behind ELB using HTTPS over port 80

### ISSUE THREAD

**Issue by nsh87** [NREL/api-umbrella#306]
I have API Umbrella behind an AWS ELB, with SSL termination at the ELB (443 -> 80 on the API Umbrella instances). On trying OAuth at `/admin/login` I'm getting a redirect URL of `https://my-domain:80/admin/login`. That's `HTTPS` over port `80`, which of course doesn't work.

It looks like the redirect URL in the request is being set to port `80`, I assume by API Umbrella....? From Google's OAuth:

```
400. That’s an error.
Error: redirect_uri_mismatch
The redirect URI in the request, https://my-domain.com:80/admins/auth/google_oauth2/callback, does not match the ones authorized for the OAuth client.
```

If I set the authorized callback URL for OAuth to use port 80, I'll just get an `ERR_SSL_PROTOCOL_ERROR` on redirect.

**Comment by nsh87** [comment]
I'm suspecting something to do with SSL termination at the LB...?

**Comment by nsh87** [comment]
I'm going to close this. Got it working by going to non-default ports.

**Comment by timothystewart6** [comment]
How did you workaround this?  This is related to https://github.com/NREL/api-umbrella/issues/329

**Comment by GUI** [comment]
There's additional documentation on potential port issues and additional configuration options in v0.14.0: https://api-umbrella.readthedocs.io/en/latest/server/listen-ports.html
