### ISSUE TITLE
Gitlab Omniauth provider

### ISSUE THREAD

**Issue by bachp** [NREL/api-umbrella#311]
I would like to see the [Omniauth Gitlab](https://github.com/linchus/omniauth-gitlab) authentication strategy included by default.

The advantage is that it can be used with gitlab.com as well as on premise Gitlab installations.

**Comment by GUI** [comment]
omniauth-gitlab has been added to the v0.14.0 release. Documentation: https://api-umbrella.readthedocs.io/en/latest/server/admin-auth.html#gitlab
