### ISSUE TITLE
Docker container conflict with nginx

### ISSUE THREAD

**Issue by thucnc** [NREL/api-umbrella#320]
I tried the docker image and mapped port 80 (443) of the container to 8090 (8091) in my existing nginx. 
Now I can access the default page at http://[mydomain], but unable to access the admin page as it always returns https://127.0.0.1/admin. Please assist.

**Comment by GUI** [comment]
I think things should work if you change API Umbrella to listen on the same ports you're trying to publicly map the host ports to (while maybe not ideal, this prevents API Umbrella from getting confused on what its public URLs should be). So for your Docker setup, modify your `config/api-umbrella.yml` file to contain:

```yml
http_port: 8090
https_port: 8091
```

And then run:

```
docker run -d --name=api-umbrella -p 8090:8090 -p 8091:8091 -v "$(pwd)/config":/etc/api-umbrella nrel/api-umbrella
```

I think that should hopefully do the trick, but let us know if not.

**Comment by GUI** [comment]
Closing this issue now, but give a shout if you're still having any issues.

**Comment by thucnc** [comment]
@GUI , the port is mapped now, but when I typed https://[mydomain]/admin it stills returns to https://127.0.0.1:8091/admin then failed to access. I tried to set the hostname in config file as below:
"
hosts:
  - hostname: gate.ahamove.com
    default: true
"

Please help

**Comment by thucnc** [comment]
It turns out our case is quite different because we have a such kind of load balancer (nginx), hence I disabled the default ssl by 

```
http_port: 8090
override_public_http_port: 443
override_public_http_proto: https
```

then run: 
`docker run -d --name=api-umbrella -p 8090:8090 -p 8091:443 -v "$(pwd)/config":/etc/api-umbrella nrel/api-umbrella`

after that, I configured my nginx to redirect to port 8090, then it works nicely.

Thanks.

**Comment by avionwd** [comment]
@thucnc can you give Nginx config that you used for?
