### ISSUE TITLE
Can Elasticsearch be used as an external database i.e., in place of MongoDB?

### ISSUE THREAD

**Issue by foobargeez** [NREL/api-umbrella#338]
Hello,
Is my understanding correct that per the [doc](http://api-umbrella.readthedocs.io/en/latest/server/db-config.html), Elasticsearch v1 (is v2 supported?) can be used as an external database?  In other words, can Elasticsearch be used for all of configuration, log and analytics (i.e., without requiring any other databases)?

Thanks in advance!

**Comment by GUI** [comment]
No, we don't currently support this. Currently, API Umbrella requires MongoDB for storing the configuration and user data. Elasticsearch is only used for analytics data.

Both databases are included in the API Umbrella package and will automatically start when you startup API Umbrella. We currently bundle Elasticsearch v2 in the API Umbrella package release, so yes, it's compatible with v2 (the doc page you found is primarily targeted for if you don't want to use the pre-packaged versions of the database included in API Umbrella for some reason--like if you already had an Elasticsearch cluster running elsewhere).

While it's on our radar that perhaps allowing a single database to be used for initial setup might be nice to aim for one day, we don't have any immediate plans for that currently.

Hope that helps, but let us know if you have any further questions.
