### ISSUE TITLE
Contemplate switching HTTP caching layer from Varnish to Apache Traffic Server

### ISSUE THREAD

**Issue by GUI** [NREL/api-umbrella#35]
We have been using Varnish 3 to provide an HTTP caching layer. However, there are a few reasons I'm pondering a switch to Apache Traffic Server to provide the HTTP caching layer. I'm not entirely convinced of making the switch, so I wanted to start an issue to track some of the potential pros/cons.

First a bit of background:

- Varnish 3's doesn't seem to handle streaming well. This [gzip+chunked responses+streaming issue](https://www.varnish-cache.org/trac/ticket/1220) has [bit us](https://github.com/18F/api.data.gov/issues/55). In general, it seems to be acknowledged that Varnish 3's streaming capabilities aren't perfect.
- We want streaming, but with Varnish 3 in the stack, it doesn't seem like we can reliably provide streaming responses.
- Varnish 4 streams everything by default, so these issues do seem to go away with Varnish 4.

So why think about Apache Traffic Server instead of just upgrading to Varnish 4? After doing more specific testing, there's been a few things that have come up:

- The most concrete issue I discovered is that Varnish appears to be hardcoded to retry requests if the backend initially times out. See [discussion 1](https://www.varnish-cache.org/lists/pipermail/varnish-misc/2010-December/019538.html) and [discussion 2](https://www.varnish-cache.org/lists/pipermail/varnish-dev/2012-November/007378.html). I don't like this behavior for GET requests (if a server is slow to respond, I don't want really want to make things worse and retry the same slow query), but this seems particularly dangerous for POST requests. The only way to prevent this from happening in Varnish is to disable keepalive, which I don't want to do. Apache Traffic Server also behaves this way by default, but it's configuration allows it to be disabled.
- The other reasons for considering Traffic Server are admittedly more nebulous and less well researched:
  - Varnish 4 does fix our previously seen streaming issue, but I've still seen some strange behavior under Varnish 4 where occasionally chunked responses get returned as non-chunked by Varnish. It's extremely sporadic, so maybe it's just a weird timing issue (maybe the whole response gets read more quickly than it can be delivered, so it just skips attempting a chunked response and delivers it non-chunked). The response body is correct under Varnish 4, but I just find it a little concerning that Varnish is sporadically changing the behavior of the backend's response. 
  - Traffic Server seems to have more of a focus on being as transparent of a proxy as possible, whereas that's less of a priority for Varnish (at least that's my take after reading various docs and mailing list threads). There are logical reasons for Varnish's stance on not trying to be a compliant proxy, but since we have less control over our potential backend servers, it makes Traffic Server's stance a little more appealing.
  - I've always had a finicky time with putting Varnish's shared memory log on a tmpfs partition, [like suggested](https://www.varnish-software.com/static/book/Tuning.html#the-shared-memory-log). This is probably more of an oversight on my part, but the tmpfs approach has always led to varnish restarts sporadically not working because it doesn't clear the tmpfs partition before trying to start the varnish server again (so it runs out of space). It's probably solvable, I've just been pleasantly surprised how easy Traffic Server is to get running without tuning like this. Removing the need to have a tmpfs partition should also make it easier to install our entire stack.
  - Traffic Server benchmarks: I've seen a few different benchmark sets that seem to indicate traffic server performs better and is more efficient than Varnish. I'd definitely like to do our own benchmarking before making this a reason, but it seems promising.

So, reasons to stick with Varnish?

- VCL: The flexibility in configuration VCL gives is quite amazing. It's allowed us to implement things like `Surrogate-Control` support just using the config file.
- Surrogate-Control: See above. We'd have to figure out how to implement `Surrogate-Control` in Traffic Server without something like VCL. I think it might be possible with some creative header manipulation, but it's something we'd need to figure out before seriously considering Traffic Server. Worse case scenario is writing a C extension.
- Plugins: Traffic Server also has plugins, but Varnish's plugin ecosystem seems much bigger. For example, I'd like to add something like [boltsort](https://github.com/vimeo/libvmod-boltsort/tree/master) (see https://github.com/NREL/api-umbrella/issues/32). There are a couple different plugin options to do such things in Varnish, but none available for Traffic Server
- Community: Varnish's community does seem bigger. Traffic Server has several large players, and seems to be growing, but Varnish seems to have more mindshare and users at this point.

So there are definitely aspects of Traffic Server that tempt me to switch, but Varnish is also widely used and a fantastic piece of software. While I mull this over, I'll continue to update this thread, but I at least wanted to get some documentation out there on why we might eventually pick one or the other.

**Comment by LukeHandle** [comment]
Hey, just interested if you have got further with this?

**Comment by Zowie** [comment]
+1

**Comment by GUI** [comment]
v0.9 of API Umbrella switches things to using TrafficServer. See the Architecture section in https://github.com/NREL/api-umbrella/pull/183 for a quick summary of why.

**Comment by chuyenim** [comment]
But Varnish does not support HTTPS.
