### ISSUE TITLE
how to add body for an api in api umbrella

### ISSUE THREAD

**Issue by srikraj8341** [NREL/api-umbrella#354]
Hi all, 
I am trying to add an api in api umbrella which has headers and body in it. Headers can be set in Global settings. I want to know where can i add body of my api

**Comment by GUI** [comment]
API Umbrella is a reverse proxy (or gateway) that sits in front of your APIs. The actual APIs will be hosted outside of API Umbrella. While API Umbrella can manipulate the headers of the response, the actual API server is responsible for the response body.

See the [architecture diagrams](https://api-umbrella.readthedocs.io/en/latest/developer/architecture.html) for more details, or the [quick start guide](https://api-umbrella.readthedocs.io/en/latest/getting-started.html#quick-tutorial) shows an example of how API Umbrella can sit in front of a Google API.

Hope that makes sense, but let us know if you have any further questions.
