### ISSUE TITLE
API_KEY_UNAUTHORIZED

### ISSUE THREAD

**Issue by srikraj8341** [NREL/api-umbrella#356]
if not ip or not ip_in_cidrs(ip, allowed_ips) then
	          return "api_key_unauthorized"
I am getting this error when i gave my aws IP as backend host. Can i know the reason ? why it is not in CIDRs?

**Comment by GUI** [comment]
The "Allowed IPs" are for configuring the public IP addresses that are allowed to hit the API Umbrella server. So these IPs would probably not be related to your AWS backend host IP.

Hope that clarifies things, but let us know if not.
