### ISSUE TITLE
Authorization problem

### ISSUE THREAD

**Issue by srikraj8341** [NREL/api-umbrella#357]
I have installed API umbrella on AWS EC2 instance and I am trying to add the backend host which also running on another EC2 instance. So while configuring API backends, do I need to add authorization? like adding AWS secret keys etc??

**Comment by GUI** [comment]
If I understand your question correctly, then you will want to secure your underlying API backend servers so they can't be hit directly (to ensure traffic goes through API Umbrella, so end users can't skip API keys, rate limiting, etc). There are a variety of ways to protect your API backend. One strategy is to enforce IP-based restrictions, so only traffic from your API Umbrella server is allowed to your API backends. That strategy is [outlined in more detail here](https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#securing-your-api-backend). Other strategies include protecting the API backend with HTTP basic auth, or requiring a secret header value be present (which API Umbrella can add to the requests).

Let us know if that doesn't answer your question, though.
