### ISSUE TITLE
[Security] 'https://dl.bintray.com/nrel/api-umbrella-ubuntu xenial Release' is not signed.

### ISSUE THREAD

**Issue by dragon28** [NREL/api-umbrella#383]
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
Executing: /tmp/tmp.ucO5YM52iv/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv-keys
379CE192D401AB61
gpg: requesting key D401AB61 from hkp server keyserver.ubuntu.com
gpg: key D401AB61: "Bintray (by JFrog) <bintray@bintray.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

sudo apt-get update

W: The repository 'https://dl.bintray.com/nrel/api-umbrella-ubuntu xenial Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.

Please kindly look into the mentioned issue.

Thanks

**Comment by GUI** [comment]
Thanks. I'm not sure we ever got the GPG signing fully setup for the apt repositories, but we'll look into it.

**Comment by GUI** [comment]
Sorry for the delay! v0.15.1 should now be properly authenticated if you follow the updated installation instructions here (note there's a new apt-key command): https://apiumbrella.io/install/ Let us know if you're still running into any issues, though.
