### ISSUE TITLE
Unable to complete quick tutorial

### ISSUE THREAD

**Issue by jtmkrueger** [NREL/api-umbrella#386]
So I've done all the steps outlined in the quick tutorial on a fresh amazon linux box.
I'm able to hit the generic static route, but when I try and visit the google maps site, I get an nginx 404 page.
```
<html>
    <head>
        <title>404 Not Found</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>404 Not Found</h1>
        </center>
        <hr>
        <center>nginx</center>
    </body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```
* I don't have an `/opt/api-umbrella/etc/nginx/backends.conf`
* I ran a `sudo /etc/init.d/api-umbrella restart` and that didn't seem to make a difference
* I tried both `localhost` and the specific domain and recieved the same results from both.

**Comment by jtmkrueger** [comment]
in the nginx log I see
```
2017-10-12T21:45:08.24280 2017/10/12 21:45:08 [error] 27389#0: *291146 "/opt/api-umbrella/embedded/apps/static-site/current/build/googleapis/index.html" is not found (2: No such file or directory), client: 10.20.103.141, server: _, request: "GET /googleapis/ HTTP/1.1", host: "api.brivity-staging.com"
```

Is it trying to hit a static site when I set up an api backend?

**Comment by jtmkrueger** [comment]
Here's what my backend config looks like:
(config)[https://i.imgur.com/nX76cXd.png]

**Comment by GUI** [comment]
Hello! This sounds like a mismatch between the "Frontend Host" setting on the API backend and the host you're running it on. You said you tried localhost and the actual hostname, but just to double check, can you try:

- Changing the "Frontend Host" to whatever domain you're currently accessing your instance at. Then be sure to publish the changes (it's easy to forget that step), and try again.
- If that doesn't work, can you try changing the "Frontend Host" to a wildcard `*`, publish the changes, and try again?

But give a shout if it's still not working.

**Comment by jtmkrueger** [comment]
The wildcard `*` did the trick thanks for pointing that out! This was so easy to set up, now on to trying to build a cluster!
