### ISSUE TITLE
Request: HTTP Method filter is not working in Analytics/Filter logs

### ISSUE THREAD

**Issue by sraghunathan** [NREL/api-umbrella#389]
I have tried to filter the log based on Request: HTTP Method, but for any method output shown as 0hits. If I remove I can able to see PUT, GET and DELETE method logs.

I'm on the latest version of api-umbrella which is running on CentOS7

**Comment by GUI** [comment]
Well, apologies for this being very belated, but this is fixed in the v0.15.1 release of API Umbrella that is now out. Thanks for filing the ticket!
