### ISSUE TITLE
Elasticsearch 5 support

### ISSUE THREAD

**Issue by david-bucsu** [NREL/api-umbrella#393]
I see that there is a branch for supporting ES 5. Is that branch ready to use? Are you planning to create a pull request from that in the near future?

**Comment by 55** [comment]
@GUI same here, any plans for the Elasticsearch 5+ support?

**Comment by GUI** [comment]
Sorry for the delay! v0.15.1 is now out and supports Elasticsearch 5, 6, and 7. The default version still being shipped with API Umbrella is still v2 to make package upgrades easier, but if you point to an external Elasticsearch database, then all those versions should now be supported.
