### ISSUE TITLE
Signup_embed.js is using a vulnerable version of jquery

### ISSUE THREAD

**Issue by mnguyen9** [NREL/api-umbrella#397]
Signup_embed.js is using jquery v.1.12.4 that contains a cross-site scripting vulnerability. This vulnerability can be used by an attacker to redirect users to a malicious site or even deface the valid website.

Recommendation is to upgrade the vulnerable library to >3.0.0-beta1.

**Comment by GUI** [comment]
Thanks for the heads up! These dependencies have now been updated in the example website provided in v0.15.1.
