### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by missinglink** [NREL/api-umbrella#402]
Heya,

I'm trying to run umbrella in a docker container and finding the Docker stuff a bit out of date :(

Dockerhub says the last push was 8 months ago? Is that right?
https://hub.docker.com/r/nrel/api-umbrella/

Also the docs for building a fresh image seem to want a `Dockerfile` but I'm only finding `Dockerfile-dev` and `Dockerfile-dev-build`. What's the difference between these two?
https://github.com/NREL/api-umbrella/blob/master/docs/developer/docker-build.md

Thanks!

**Comment by vegasbrianc** [comment]
@missinglink I actually build the container locally and it works fine.

Copy the Dockerfile locally

`docker build -t v15.1 .`

**Comment by missinglink** [comment]
Hi sorry I opened this a year ago and I don't even remember what this repo does.

I suspect the issue probably got fixed at some point so I'm closing it.
