### ISSUE TITLE
Unable to download api-umbrella in ubuntu-16.04

### ISSUE THREAD

**Issue by komalacogxar** [NREL/api-umbrella#404]
I am following the link https://api-umbrella.readthedocs.io/en/latest/getting-started.html for api-umbrella installation. 
But i am getting following error while running apt-get update command-
W: The repository 'https://dl.bintray.com/nrel/api-umbrella-ubuntu xenial Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Please let me the problem.

**Comment by remcoboerma** [comment]
Same here when updating. Related to #383

**Comment by GUI** [comment]
Sorry for the delay! v0.15.1 should now be properly authenticated if you follow the updated installation instructions here (note there's a new `apt-key` command): https://apiumbrella.io/install/ Let us know if you're still running into any issues, though.
