### ISSUE TITLE
[Question] How to redirect HTTP -> HTTPS in admin?

### ISSUE THREAD

**Issue by medeirosrafael** [NREL/api-umbrella#407]
I'm configuring API Umbrella behing ELB, everything is working.. But, when i try access http://my-domain
it doenst redirect to https://my-domain. If i access https://my-domain it works as well, but i want redirect http -> https in admin interface.

How can i do it?

**Comment by remcoboerma** [comment]
The only option right now is to redirect from within the client. Serve http and https, have some JS detect http and redirect to https.
I'm not an api-umbrella developer, so I'm investigating the same issue.
My bet is that there might be an option using the error templates but I haven't had time yet to fully dive in.

**Comment by GUI** [comment]
Apologies for the delayed response. The new API Umbrella v0.15.1 release is now out, and this should redirect all website traffic to HTTPS by default. Let us know if you're still seeing any issues.

**Comment by wub1990** [comment]
Hey, I am using API Umbrella v0.15.1 but i still encounter the problem descript by medeirosrafael

![2019-06-20_17-20-45 (2)](https://user-images.githubusercontent.com/35376196/59861153-95cf5280-9380-11e9-9acf-f74b0cc1da4d.png)
