### ISSUE TITLE
missing LSB tags and overrides

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#42]
As a note, when installing api-umbrella on Debian 7, I get the following warning:
```
Unpacking api-umbrella (from api-umbrella_0.6.0-1_amd64.deb) ...
Setting up api-umbrella (0.6.0-1) ...
update-rc.d: using dependency based boot sequencing
insserv: warning: script 'api-umbrella' missing LSB tags and overrides
```

**Comment by GUI** [comment]
Thanks for reporting this. These warnings should now be fixed in master by https://github.com/NREL/omnibus-api-umbrella/commit/37c4d95b6d560a4c7c85917c1b87b609035c4c6e This will be fixed in the v0.7 packages that I'm going to try to get out this week.
