### ISSUE TITLE
Ubuntu 18.04 - Deb Package?

### ISSUE THREAD

**Issue by hinokata** [NREL/api-umbrella#432]
I see a couple of folks have asked (with no reply) about Ubuntu 18.04, so I thought I would ask as well. Are there any plans to add an 18.04 binary package?

**Comment by CS3dev** [comment]
I will echo the request that 18.04 be made binary.

**Comment by supersexy** [comment]
Yes, please - 18.04 is a good server distro, please support that, thanks!

**Comment by LuizComelli** [comment]
Boa tarde,

Estou no aguardo dessa versão.

**Comment by GUI** [comment]
Ubuntu 18.04 packages are now available for v0.15.1: https://apiumbrella.io/install/ Sorry for the delay in the packages, but let us know if you run into any issues with them.

**Comment by CS3dev** [comment]
Hello 

As time marches on so does your need to confirm open jobs.
Especially on the short notice pop up job.This is part of the constant driving pressure of being a Call Steward.

Our latest addition to the phone sheet allows you set a timer on how long an offer of work will remain on the table !

Set the timer on a per job basis, and let the software clear slots for you automatically, updating logs along the way !

This keeps you moving forward  to the next possible solution, as soon as possible.Leave No Call Unfilled with Call Steward !

Schedule your online demo today !




  Ed Hills, Owner
www.CallSteward.com
1-855-LOAD-OUT (562-3688)
sales@callsteward.com
  Unsubscribe [http://fslink.callsteward.com/email/track/unsubscribe?hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7Imxpb24iOiI2YjI4IiwiZ29yaWxsYSI6IjdhODU2MDBiIiwiaG9yc2UiOiJyZXBseSthZTZ4aHI1c2tqNzc2enBleGRuY3k1bjIzM3pvemV2Ym5oaGJveW52NjRAcmVwbHkuZ2l0aHViLmNvbSIsImNhbWVsIjoiODJiYjU1ZmMifSwiaWF0IjoxNTYwODc1ODM1fQ.Hy8NUSXalQFNhizKIJAUEfAYUIF21q82-TAcPXIw9io]

**Comment by CS3dev** [comment]
Hello 

As time marches on so does your need to confirm open jobs.
Especially on the short notice pop up job.This is part of the constant driving pressure of being a Call Steward.

Our latest addition to the phone sheet allows you set a timer on how long an offer of work will remain on the table !

Set the timer on a per job basis, and let the software clear slots for you automatically, updating logs along the way !

This keeps you moving forward  to the next possible solution, as soon as possible.Leave No Call Unfilled with Call Steward !

Schedule your online demo today !




  Ed Hills, Owner
www.CallSteward.com
1-855-LOAD-OUT (562-3688)
sales@callsteward.com
  Unsubscribe [http://fslink.callsteward.com/wf/click?upn=L74lNIYv-2BansIsqRnAwFOz-2BCswAA6sVevDYGKeRdOAs85gxRmLY1TgnLGzm1riQI8Br4zkNU4fiaisvbqUTr98Sm4VA1JgyUs1nDKTTL7pjSe9s8BrLHAyNwkYswHYTRq5hA53wuaO0-2BOc3HvzIqksgLCfzq4QCYkZmdCdMwNakCPnUMtQfkKUTDDp8WNcdjDBFiDW-2FNdTXx8mTd0-2BDA6-2B6EaiDWH48RLlGoWzBUnBDwVGa0EvF4jGY3yAWCZyx06Ldeb5Oq51KeuxaxcyXcmXjaCO5IuPzenFPTj6OyoALS-2Bewy61Y5eOaOJWSmdVMhY6Jaj6bgJA3MABATTwtBIdxWOMY-2BPYK9LGSyc5ctvwbuArm7aqGM99NyGpganrLWCZY9-2FPA2Nk1c29lsXnJYCBjaIOOtyX8QkaQEy6WTxpy6sWElpW8g7i64SMLqcdEO-2BnteblV7RWHOs8ri4gLuRB-2BR2RJ3ZvA8mPFyy6N5Qxuh-2FjcWX08I7aa-2FSyewTnAk-2BRhbkYShCv1Xk9JBzRzoCbgQBHzvb9rfJM77L40hQAk-3D_s5UH8bhnBaopYjthcNSRcS-2FNJmfaOirzLIYNon-2BvAuf0ivk0Wyg3la33fKJJML96Qb2EsrQUjp-2Ftvb3WOkS2eeDskhAn1D8eVffqGM1wu0yxrcqmqW3v4RTXn6B-2Ft9CELscuL9eiNff18JpK6vKYXlYWco6fMauT7aiZAGhUUfjjRDUxXQhGZJ3UhbyeTswkrAEsZqfVxQ3Dpllg-2FmgsrCG9NjM7UBTbIBlEVU3i-2BSuUHBw5YT0gm0lP8NITnNUenaOg-2FLZN1UzOAK3tjKbYZOOPCbzDiAEemZNRIpo-2BInFiRV-2B02L98T-2FP18gsgFlp2PWH6e7v7dSJrHA8i0FM11A-3D-3D]
