### ISSUE TITLE
maxmind - .dat file not downloading

### ISSUE THREAD

**Issue by mfrederico** [NREL/api-umbrella#440]
As of January 02, 2019 maxmind no longer is giving access to the legacy GeoLiteCityv6-beta data 

This causes compile (make) to fail when it attempts to download the database.

My workaround was to modify the build file to grab: 
https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

And it proceeds with compile.

**Comment by GUI** [comment]
Thanks for filing this ticket, but sorry for the delay in following up. API Umbrella v0.15.1 has been released and it includes a switch to GeoLite2 data to address this.
