### ISSUE TITLE
api-umbrella admin gui reorder url prefixes seems not to work at all

### ISSUE THREAD

**Issue by pauldzy** [NREL/api-umbrella#450]
Hello,

Using the api-umbrella admin gui through api.data.gov I would like to use the "reorder" button to restructure my url prefixes into a better organization.  However no amount of fumbling about will persist the reordering.  This includes making sure to press the DONE button and then the SAVE button and even the PUBLISH step.  When I return the url prefixes are back to their original first-in-at-the-top ordering.

Using API Umbrella Version 0.16.0-pre1 with Chrome 73.

Thanks,
Paul

**Comment by leandrodro** [comment]
Did you manage to find out something on this topic?

**Comment by pauldzy** [comment]
Nope, not really expecting a fix at this point.  Thanks for the reminder as I will just close the ticket.  Does your organization have an alternative api gateway they are moving towards?

**Comment by science695** [comment]
Hello @pauldzy, I have occasionally had a need to re-order things in the umbrella gui.

Are you talking about the priority between different api backends, or the urls inside each one?

I have been able to update priority between the backends, but no luck on the urls inside.

For the backend priority, I have the admin apis in a postman and I call Get route with the id from the gui, I remove the "api" level from the object, and then send it as a PUT to update it. This did not work on the urls though, which makes me wonder if the order is even being saved in the DB.
