### ISSUE TITLE
Backend not connecting to IP Address for API

### ISSUE THREAD

**Issue by devsetgo** [NREL/api-umbrella#463]
First, I have Api-Umbrella running in docker (0.15.1). I cannot use the containers IP address (server IP) for the backend. I have tried having the backend host with and without the port.  As a note, I tried using a domain name on the API and it works, plus if I access via the IP and Port directly I can access.

The error received is a 504 Gatway time-out.

Any thoughts on why Api-Umbrella is failing?

![image](https://user-images.githubusercontent.com/16019894/60770011-7173b580-a0a4-11e9-9c3e-2508c64d1691.png)

**Comment by leandrodro** [comment]
Did you manage to find out something on this topic?

**Comment by devsetgo** [comment]
I gave up trying to API Umbrella and switched to Traefik for my needs. I built a simple middleware to deal with authentication and protect API endpoints that are internal/external.

Good luck.

**Comment by Luca-Castelnuovo** [comment]
Is there an update on this?
