### ISSUE TITLE
502 Bad Gateway - no resolver defined

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#49]
I was able to get a basic query to work using the [Getting Started guide](http://nrel.github.io/api-umbrella/docs/getting-started/), after some [minor tweaking of the URL parameters](http://apinf.com/google/maps/api/geocode/json?address=Tampere&api_key=lrJUOcn3RFb0i3vH48qYalQwnz4LxE1FXfnac6BY).

When I add a [second API](http://apinf.com/avoindata/) and [call its URL](http://apinf.com/avoindata/tags?api_key=lrJUOcn3RFb0i3vH48qYalQwnz4LxE1FXfnac6BY), I get a **502 Bad Gateway**.

**Comment by GUI** [comment]
As a quick heads up, the [new v0.7 packages](https://github.com/NREL/api-umbrella/blob/master/CHANGELOG.md#070--2015-02-08) that have been released should solve this issue with much better error validation surrounding the API Backend forms. Now you won't be able to save the form without filling in the backend section (and we've made a variety of other changes to try to improve the flow and error handling).
