### ISSUE TITLE
External MongoDB

### ISSUE THREAD

**Issue by sziniuk-blackbird** [NREL/api-umbrella#501]
Hi,
I just curious is it possible to use external mongoDB?
For example: via changing mongodb url in api-umbrella.yml like that
url: "mongodb://db_user:db_pass@db_host:27017/"

Is it compatible with AWS DocumentDB?

**Comment by sziniuk-blackbird** [comment]
resolved

**Comment by vudq** [comment]
> resolved

What is your solution?
