### ISSUE TITLE
Question: does api-umbrella support more nuanced integration with REST api frameworks like Spring Boot?

### ISSUE THREAD

**Issue by aubrey-y** [NREL/api-umbrella#510]
As far as I can tell from the documentation, it seems like api-umbrella is meant to live as an entirely separate layer from the rest api itself. By using api-umbrella, I have to host like one of your docker containers and use your UI exclusively to distribute api keys?

I was more interested in api management with more involved maven/java integration so that I could create my own UI and decide what criteria to accept in exchange for giving api keys. Sounds like that won't be possible?

**Comment by science695** [comment]
There are admin apis that you can use to create and update api keys, so can run a system that authorizes and gets api keys from umbrella to give out.
