### ISSUE TITLE
Cannot Start Docker Dev Image

### ISSUE THREAD

**Issue by tpandya** [NREL/api-umbrella#531]
Dock Image fails to start for Dev with the below error:
Starting api-umbrella_app_1 ... done
Attaching to api-umbrella_app_1
app_1  | + mkdir -p /etc/api-umbrella
app_1  | + echo 'app_env: development'
app_1  | + echo 'http_port: 8100'
app_1  | + echo 'https_port: 8101'
app_1  | + mkdir -p /build/.task
app_1  | + ln -snf /build/.task /app/.task
app_1  | + mkdir -p /build/build/work/stage/opt/api-umbrella/var/log
app_1  | + ln -snf /build/build/work/stage/opt/api-umbrella /opt/api-umbrella
app_1  | + ln -snf /build/build/work/stage/opt/api-umbrella/var/log /var/log/api-umbrella
app_1  | + ln -snf /build/build/work /app/build/work
app_1  | + mkdir -p /build/test/tmp/run
app_1  | + mkdir -p /app/test/tmp
app_1  | + ln -snf /build/test/tmp/run /app/test/tmp/run
app_1  | + mkdir -p /app/build/work/tasks/app-deps/admin-ui/yarn/_persist/node_modules
app_1  | + ln -snf /app/build/work/tasks/app-deps/admin-ui/yarn/_persist/node_modules /app/src/api-umbrella/admin-ui/node_modules
app_1  | + mkdir -p /app/build/work/tasks/test-deps/bundle/_persist/.bundle
app_1  | + ln -snf /app/build/work/tasks/test-deps/bundle/_persist/.bundle /app/.bundle
app_1  | + mkdir -p /app/build/work/tasks/app-deps/web-app/bundle/_persist/.bundle
app_1  | + ln -snf /app/build/work/tasks/app-deps/web-app/bundle/_persist/.bundle /app/src/api-umbrella/web-app/.bundle
app_1  | + mkdir -p /app/src/api-umbrella/admin-ui/tmp
app_1  | + chmod 1777 /app/src/api-umbrella/admin-ui/tmp
app_1  | + exec /app/docker/dev/docker-start
app_1  | + make
app_1  | make: *** No targets specified and no makefile found.  Stop.
api-umbrella_app_1 exited with code 2

**Comment by onaralili** [comment]
did you find a solution for this issue?
