### ISSUE TITLE
Interface translations

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#60]
Story
------
As a non-English speaking user
I would appreciate if the userface elements, such as inline-help, were translated
So that I can easily navigate the interface

Example
-----------
As a non-English language speaker, I
  1. Look for a link to 'change language'
  2. Click to select the appropriate language for my needs

Dependencies/relationships
-----------------------------------
* Internationalization (i18n) 
* Localization (l10n)
* Accessibility (a11y)

Support this issue
----------------------
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=6023540)](https://www.bountysource.com/issues/6023540-interface-translations?utm_source=6023540&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by ccsr** [comment]
I have backed this up with bounty on https://www.bountysource.com/issues/6023540-interface-translations

**Comment by GUI** [comment]
I forgot to mention this, but a while back, I laid the foundation for both server-side and client-side translations. Both use the Rails `config/locales/*.yml` files, so all the translations should be consolidated there. When working on new features I've tried to only use localized strings in the UI. There's still a fair bit of work to update all the rest of the existing UI to use localized strings, but some of it is in place (admin menus and I think most of the API Backends form).

Here's the current translations: https://github.com/NREL/api-umbrella-web/blob/master/config/locales/en.yml

I've also been playing with some different services to help manage translations. Here's our project on OneSky: https://nrel-gov.oneskyapp.com/collaboration/project?id=47156 If you signup, they provide an interface for managing translations, tracking progress, dealing with updates, etc. Or if you'd prefer to stick to the raw YAML files and git, pull requests are welcome. Or if you have any other preferred ways of dealing with translations, I'm more than open to suggestions.

So while this isn't done yet, hopefully these pieces are at least a start towards making translating the entire app easier.

**Comment by brylie** [comment]
Can we use a service such as [Transifex](https://www.transifex.com/organizations/add/) to collaborate on these translations? We can help with the Finnish translation.

**Comment by GUI** [comment]
Did you check out our translations on the [OneSky account](https://nrel-gov.oneskyapp.com/collaboration/project?id=47156) I linked to? OneSky should be a service that's very similar to Transifex. I had played with both services and mainly used OneSky since it seemed a bit easier to figure out than Transifex, but that's just me. I've never actually done translations before, so if you're familiar with Transifex, or you'd simply prefer that service for any reason, just let me know and I'm happy to get us setup over there instead.

**Comment by brylie** [comment]
Ah, my bad. I obviously didn't catch that link, sorry.

**Comment by perfaram** [comment]
Hmmm, could translate to french.

**Comment by kyyberi** [comment]
I can do Finnish translation

**Comment by GUI** [comment]
@perfaram: I saw you added the French translations in OneSky. Thank you! I've pulled those into master at https://github.com/NREL/api-umbrella-web/commit/603a77e502135b040c4afd47abc34d8d3524378b

**Comment by brylie** [comment]
Yay Team Finland (@kyyberi and Vesa)! 30% completed just now :-)

**Comment by kyyberi** [comment]
92,8% :D I just got home and had some time to translate a few more

**Comment by perfaram** [comment]
Started to translate in German

**Comment by brylie** [comment]
Great job with the Finnish translation!

Out of curiosity and since we have so many translators working right now, how can we check the i18n string coverage in the API Umbrella? I.e. how can we ensure that the current translation efforts are covering a substantial portion of the UI strings?

**Comment by GUI** [comment]
Finnish, French, Italian, and Russian translations have been included in the [new v0.7 packages](https://github.com/NREL/api-umbrella/blob/master/CHANGELOG.md#070--2015-02-08) (with some translations started in German and Spanish too). I really want to thank everyone on this issue for getting the translation process rolling and also helping out with the actual translation work too! I hope this will begin to make API Umbrella more useful to others.

A few notes on this translation front:

- I think the admin menus and most of the API Backends form should be translated. However, please note that we still haven't switched over a number of other places in the admin to be translation-friendly. So even though we have a number of languages that have translated 100% of the phrases according to OneSky, there will still be more work before all the interface bits in the admin are fully translated. But I'm hoping this will be a good start. I'll try to do a more thorough internationalization of the admin UI at some point, but feel free to let us know what's missing.
- I think I forgot to mention, but the language used in the admin is determined based on your browser's `Accept-Language` header. So right now, the admin language used isn't an option you choose anywhere, but instead it will be based only on what languages we support and what your browser says is your preferred language. But as a sad mono-lingual person myself, I don't exactly know how well this works. So from the international crowd I'd love to know: Does this simple browser-based approach work well for you? Or would you prefer an explicit preference that you have to set on your account to choose a language?

**Comment by GUI** [comment]
Actually, crap, it looks like we made a mistake in packaging v0.7 that will mean the admin will be broken if your browser tries to load a non-English language. I thought I had tested this, but I guess not. Sorry!

I'll try to get v0.7.1 released within the next couple days to fix this. In the meantime, if you were interested in the admin interface translations, you may want to hold off for a couple days until this ticket is closed: https://github.com/NREL/api-umbrella/issues/103

**Comment by GUI** [comment]
And as a quick heads up, [v0.7.1 packages](https://github.com/NREL/api-umbrella/blob/master/CHANGELOG.md#071--2015-02-11) have been released to fix this glaring translation oversight in v0.7.0 (and more tests have been added to ensure this doesn't happen again). Sorry about that! So if you want to give any of the different languages a spin, then v0.7.1 should be the version for you.

**Comment by brylie** [comment]
@NRELAdmin @GUI I am closing this issue, as we have crowdsourced the translation effort.

**Comment by brylie** [comment]
@NRELAdmin please consider how to distribute the [$250 bounty](https://www.bountysource.com/issues/6023540-interface-translations/developers).
