### ISSUE TITLE
strange checkbox behavior in Firefox browser

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#63]
When configuring an admin group on the **Add Admin Group** page ( admin/#/admin_groups/new ), the checkboxes are not behaving as expected.

Observed behavior
----------------------
* When **single clicking** a checkbox, the checkbox is highlighted, but no checkmark appears
* When **double clicking** a checkbox the highlighting is removed and the checkmark appears

Expected behavior
------------------
* When **single clicking** a checkbox, the checkmark should appear
* When **double clicking** a checkbox the checkmark should appear and disappear (one event with each click)

**Comment by GUI** [comment]
Whoops, this definitely slipped past me, but this should be fixed in v0.9: https://github.com/18F/api.data.gov/issues/271
