### ISSUE TITLE
How to change the index page?

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#69]
## Story

As an API Umbrella administrator
I would like to change the appearance of the portal front page
So that I can add specific colors, text, images, and other details for our particular instance
## Specifics

We have a designer who has created a bootstrap template that we would like to use as our portal page. Where do we put this template so that it will be displayed instead of the default API Umbrella page? What file do we edit if we want to change the default API Umbrella page?

**Comment by GUI** [comment]
Well, this is absurdly belated (sorry!), but here's finally some documentation on how to configure website backends: https://api-umbrella.readthedocs.io/en/latest/admin/website-backends.html Website backends were originally added in the v0.8.0 release (released on 2015-04-26) as a way to make all this easier:

- Any non-API URL will get routed to the website backend (so there shouldn't be some of the hurdles I originally outlined in adding new content at new paths).
- Different websites can be served for different hostnames.
- There's an interface in the admin for defining the website backends.

**Comment by brylie** [comment]
Well, this feature request pretty much spawned the APInf project, so "water under the bridge".
