### ISSUE TITLE
[dev] Not starting NFS kernel daemon: no exports.

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#74]
As a note, when setting up the development server on Ubuntu 14.10, I get the following message when installing the NFS dependencies:

```
Creating config file /etc/default/nfs-kernel-server with new version
 * Not starting NFS kernel daemon: no exports.
```

**Comment by GUI** [comment]
I think this has been addressed by updates to the documentation noting the NFS requirements.
