### ISSUE TITLE
[dev] VT-x is not available. (VERR_VMX_NO_VMX)

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#75]
When trying to set up a development environment on Ubuntu 14.10, I get the following error after running `vagrant up` (error message copied from VirtualBox after attempting to start the VM):

```
Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
Console
Interface: 
IConsole {8ab7c520-2442-4b66-8d74-4ff1e195d2b6}
```

Is this possibly related to #74?

**Comment by GUI** [comment]
I think this has been addressed by updates to the documentation noting the 64 bit requirements.
