### ISSUE TITLE
[dev] kernel requires x86-64 CPU

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#76]
When setting up a dev environment on an i686 32bit computer, I get the following notice:

```
This kernel requires an x86-64 CPU, but only detected an i686 CPU.
Unable to boot - please use a kernel appropriate for your CPU.
```

Is this simply a documentation issue, or will it be advisable to build a 32bit development environment?

**Comment by GUI** [comment]
I think this has been addressed by updates to the documentation noting the 64 bit requirements.
