### ISSUE TITLE
Questions on deployment/development with api-umbrella

### ISSUE THREAD

**Issue by aatong** [NREL/api-umbrella#79]
Hi, I am a newbie to all of this and hoping i can get some help or questions answered. I tried to install api-umbrella project through 'npm' on my windows machine and am hitting a lot of issues. Basically, even after following directions to install node-gyp, python, and other windows sdks, I still can't get it to work. I know recommended way is to deploy it through Vagrant for development, but am wondering then how individuals would package/deployment this in real environment? There's an rpm provided but that wouldn't be picking up the stuffs that I may need to change etc... Am new to github and all of this, so it'd be great if someone can help me answer these questions. Thanks!

**Comment by GUI** [comment]
Very sorry for the long delay. I've finally added a documentation page on deploying the components from git, independent of API Umbrella packaged released: http://nrel.github.io/api-umbrella/docs/deployment/ If you run into any issues with that process, or you have any other questions about deployment, feel free to re-open.
