### ISSUE TITLE
Cookbook api-umbrella not found

### ISSUE THREAD

**Issue by perfaram** [NREL/api-umbrella#80]
When doing ```vagrant up```, I get : 
```[.......]
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: Starting Chef Client, version 11.16.4
==> default: [2014-12-24T15:51:40+00:00] INFO: *** Chef 11.16.4 ***
==> default: [2014-12-24T15:51:40+00:00] INFO: Chef-client pid: 4372
==> default: [2014-12-24T15:51:42+00:00] INFO: Setting the run_list to ["recipe[api-umbrella::development]"] from CLI options
==> default: [2014-12-24T15:51:42+00:00] INFO: Run List is [recipe[api-umbrella::development]]
==> default: [2014-12-24T15:51:42+00:00] INFO: Run List expands to [api-umbrella::development]
==> default: [2014-12-24T15:51:42+00:00] INFO: Starting Chef Run for api.vagrant
==> default: [2014-12-24T15:51:42+00:00] INFO: Running start handlers
==> default: [2014-12-24T15:51:42+00:00] INFO: Start handlers complete.
==> default: Compiling Cookbooks...
==> default: 
==> default: Running handlers:
==> default: [2014-12-24T15:51:42+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2014-12-24T15:51:42+00:00] ERROR: Exception handlers complete
==> default: [2014-12-24T15:51:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: Chef Client failed. 0 resources updated in 2.28325005 seconds
==> default: [2014-12-24T15:51:42+00:00] ERROR: Cookbook api-umbrella not found. If you're loading api-umbrella from another cookbook, make sure you configure the dependency in your metadata
==> default: [2014-12-24T15:51:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
Any idea about this ? I know really nothing about Chef...

EDIT : I'm running OSX 10.10

**Comment by perfaram** [comment]
Nobody answered, so I guess nobody knows the reason(s)...
BTW, I just removed everything of api-umbrella (including the last install I made before there was easy install system), then removed vagrant, reinstalled it, retried - it worked.

**Comment by perfaram** [comment]
Thanks to you all for making such a great tool !

**Comment by darylrobbins** [comment]
I'm seeing the exact same issue on OSX 10.10 when trying to get the environment setup for the first time. I will try perfaram's suggested fix. My logs are identical.

I confirmed that the /vagrant folder is being mounted properly via NFS. I also tried setting `chef.synced_folder_type = "nfs"` but to no avil.

**Comment by darylrobbins** [comment]
Removing vagrant and my vagrant data directory resolved the issue. My best guess is this could have been related to one of the Vagrant plugins I had installed.

**Comment by perfaram** [comment]
@darylrobbins : Most probably, yes

**Comment by darylrobbins** [comment]
For future reference, this problem occurs due to an incompatibility with the vagrant-berkshelf plugin, which is kind of an unfortunate plugin not to play nicely with.

The fix is: `vagrant plugin uninstall vagrant-berkshelf`

**Comment by perfaram** [comment]
Thanks for the update !
