### ISSUE TITLE
Cross-Origin Resource Sharing (CORS) support?

### ISSUE THREAD

**Issue by brylie** [NREL/api-umbrella#81]
As an API manager,
I would like to quickly add CORS support to any defined API
So that developers can make cross-origin requests easily

Proposal (1)- documentation
-----------------
Add 'cookbook' style CORS recipe to API Umbrella docs, describing what header values to add/modify to enable CORS support on proxy endpoints.

Proposal (2) - toggle widget
----------------
Create 'Enable CORS' toggle switch on endpoint configuration screen, with corresponding informative text of the implications of enabling CORS.

Proposal (3) - Auto-configure button
----------------
Add a button to the header configuration section of the UI to "Add CORS headers". The header fields will be created and user-editable.

**Comment by kyyberi** [comment]
+1

**Comment by brylie** [comment]
@kyyberi sent me a link to his [CORS implementation](https://github.com/kyyberi/lentodiilit/blob/master/api/index.php#L228).

**Comment by GUI** [comment]
Belatedly closing this, since this was part of the v0.8 release.

**Comment by ashakunt** [comment]
@GUI : If I understand correct, then the required changeset (for modifying response headers) is not a part of the current available debian (at apiumbrella.io/download | api-umbrella_0.8.0-1_amd64.deb). Do you have any idea when the latest version (v0.8.16) is going to be available?
